<?php

/**
 * Basecontrato_fornecedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $numero_contrato
 * @property integer $filial_id
 * @property integer $fornecedor_id
 * @property integer $tipo_manutencao_id
 * @property decimal $valor_mensal
 * @property integer $ano_referencia
 * @property sfGuardUf $sfGuardUf
 * @property preventiva_tipo $preventiva_tipo
 * @property fornecedor $fornecedor
 * 
 * @method integer             getNumeroContrato()     Returns the current record's "numero_contrato" value
 * @method integer             getFilialId()           Returns the current record's "filial_id" value
 * @method integer             getFornecedorId()       Returns the current record's "fornecedor_id" value
 * @method integer             getTipoManutencaoId()   Returns the current record's "tipo_manutencao_id" value
 * @method decimal             getValorMensal()        Returns the current record's "valor_mensal" value
 * @method integer             getAnoReferencia()      Returns the current record's "ano_referencia" value
 * @method sfGuardUf           getSfGuardUf()          Returns the current record's "sfGuardUf" value
 * @method preventiva_tipo     getPreventivaTipo()     Returns the current record's "preventiva_tipo" value
 * @method fornecedor          getFornecedor()         Returns the current record's "fornecedor" value
 * @method contrato_fornecedor setNumeroContrato()     Sets the current record's "numero_contrato" value
 * @method contrato_fornecedor setFilialId()           Sets the current record's "filial_id" value
 * @method contrato_fornecedor setFornecedorId()       Sets the current record's "fornecedor_id" value
 * @method contrato_fornecedor setTipoManutencaoId()   Sets the current record's "tipo_manutencao_id" value
 * @method contrato_fornecedor setValorMensal()        Sets the current record's "valor_mensal" value
 * @method contrato_fornecedor setAnoReferencia()      Sets the current record's "ano_referencia" value
 * @method contrato_fornecedor setSfGuardUf()          Sets the current record's "sfGuardUf" value
 * @method contrato_fornecedor setPreventivaTipo()     Sets the current record's "preventiva_tipo" value
 * @method contrato_fornecedor setFornecedor()         Sets the current record's "fornecedor" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecontrato_fornecedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contrato_fornecedor');
        $this->hasColumn('numero_contrato', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('filial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fornecedor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_manutencao_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('valor_mensal', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('ano_referencia', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUf', array(
             'local' => 'filial_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('preventiva_tipo', array(
             'local' => 'tipo_manutencao_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('fornecedor', array(
             'local' => 'fornecedor_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}