<?php

/**
 * BasePeriodicidade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property Doctrine_Collection $preventiva_periodicidades
 * 
 * @method string              getNome()                      Returns the current record's "nome" value
 * @method Doctrine_Collection getPreventivaPeriodicidades()  Returns the current record's "preventiva_periodicidades" collection
 * @method Periodicidade       setNome()                      Sets the current record's "nome" value
 * @method Periodicidade       setPreventivaPeriodicidades()  Sets the current record's "preventiva_periodicidades" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeriodicidade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('periodicidade');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Preventiva as preventiva_periodicidades', array(
             'local' => 'id',
             'foreign' => 'periodicidade_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}