<?php

/**
 * BasesfGuardGramAfiliado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $afiliado_id
 * @property integer $gram_id
 * @property Afiliado $Afiliado
 * @property sfGuardGram $Gram
 * 
 * @method integer             getAfiliadoId()  Returns the current record's "afiliado_id" value
 * @method integer             getGramId()      Returns the current record's "gram_id" value
 * @method Afiliado            getAfiliado()    Returns the current record's "Afiliado" value
 * @method sfGuardGram         getGram()        Returns the current record's "Gram" value
 * @method sfGuardGramAfiliado setAfiliadoId()  Sets the current record's "afiliado_id" value
 * @method sfGuardGramAfiliado setGramId()      Sets the current record's "gram_id" value
 * @method sfGuardGramAfiliado setAfiliado()    Sets the current record's "Afiliado" value
 * @method sfGuardGramAfiliado setGram()        Sets the current record's "Gram" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardGramAfiliado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_gram_afiliado');
        $this->hasColumn('afiliado_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('gram_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Afiliado', array(
             'local' => 'afiliado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGram as Gram', array(
             'local' => 'gram_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}