<?php

/**
 * Basepreventiva_tipo_cabecalho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cabecalho_id
 * @property integer $preventiva_tipo_id
 * @property Cabecalho $Cabecalho
 * @property preventiva_tipo $preventiva_tipo
 * 
 * @method integer                   getCabecalhoId()        Returns the current record's "cabecalho_id" value
 * @method integer                   getPreventivaTipoId()   Returns the current record's "preventiva_tipo_id" value
 * @method Cabecalho                 getCabecalho()          Returns the current record's "Cabecalho" value
 * @method preventiva_tipo           getPreventivaTipo()     Returns the current record's "preventiva_tipo" value
 * @method preventiva_tipo_cabecalho setCabecalhoId()        Sets the current record's "cabecalho_id" value
 * @method preventiva_tipo_cabecalho setPreventivaTipoId()   Sets the current record's "preventiva_tipo_id" value
 * @method preventiva_tipo_cabecalho setCabecalho()          Sets the current record's "Cabecalho" value
 * @method preventiva_tipo_cabecalho setPreventivaTipo()     Sets the current record's "preventiva_tipo" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepreventiva_tipo_cabecalho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preventiva_tipo_cabecalho');
        $this->hasColumn('cabecalho_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('preventiva_tipo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cabecalho', array(
             'local' => 'cabecalho_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('preventiva_tipo', array(
             'local' => 'preventiva_tipo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}