<?php

/**
 * BaseOrcamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $controle_id
 * @property string $responsavel
 * @property decimal $subtotalGeral
 * @property decimal $subtotalMaterial
 * @property decimal $subtotalDiversos
 * @property decimal $subtotal20
 * @property decimal $subtotalPini
 * @property decimal $subtotalPiniBdi
 * @property decimal $total
 * @property string $anexo
 * @property string $informacao
 * @property string $observacao
 * @property string $usuario
 * @property datetime $data_hora
 * @property string $email
 * @property boolean $edicao
 * @property Manutencao $Orcamentos
 * 
 * @method integer    getControleId()       Returns the current record's "controle_id" value
 * @method string     getResponsavel()      Returns the current record's "responsavel" value
 * @method decimal    getSubtotalGeral()    Returns the current record's "subtotalGeral" value
 * @method decimal    getSubtotalMaterial() Returns the current record's "subtotalMaterial" value
 * @method decimal    getSubtotalDiversos() Returns the current record's "subtotalDiversos" value
 * @method decimal    getSubtotal20()       Returns the current record's "subtotal20" value
 * @method decimal    getSubtotalPini()     Returns the current record's "subtotalPini" value
 * @method decimal    getSubtotalPiniBdi()  Returns the current record's "subtotalPiniBdi" value
 * @method decimal    getTotal()            Returns the current record's "total" value
 * @method string     getAnexo()            Returns the current record's "anexo" value
 * @method string     getInformacao()       Returns the current record's "informacao" value
 * @method string     getObservacao()       Returns the current record's "observacao" value
 * @method string     getUsuario()          Returns the current record's "usuario" value
 * @method datetime   getDataHora()         Returns the current record's "data_hora" value
 * @method string     getEmail()            Returns the current record's "email" value
 * @method boolean    getEdicao()           Returns the current record's "edicao" value
 * @method Manutencao getOrcamentos()       Returns the current record's "Orcamentos" value
 * @method Orcamento  setControleId()       Sets the current record's "controle_id" value
 * @method Orcamento  setResponsavel()      Sets the current record's "responsavel" value
 * @method Orcamento  setSubtotalGeral()    Sets the current record's "subtotalGeral" value
 * @method Orcamento  setSubtotalMaterial() Sets the current record's "subtotalMaterial" value
 * @method Orcamento  setSubtotalDiversos() Sets the current record's "subtotalDiversos" value
 * @method Orcamento  setSubtotal20()       Sets the current record's "subtotal20" value
 * @method Orcamento  setSubtotalPini()     Sets the current record's "subtotalPini" value
 * @method Orcamento  setSubtotalPiniBdi()  Sets the current record's "subtotalPiniBdi" value
 * @method Orcamento  setTotal()            Sets the current record's "total" value
 * @method Orcamento  setAnexo()            Sets the current record's "anexo" value
 * @method Orcamento  setInformacao()       Sets the current record's "informacao" value
 * @method Orcamento  setObservacao()       Sets the current record's "observacao" value
 * @method Orcamento  setUsuario()          Sets the current record's "usuario" value
 * @method Orcamento  setDataHora()         Sets the current record's "data_hora" value
 * @method Orcamento  setEmail()            Sets the current record's "email" value
 * @method Orcamento  setEdicao()           Sets the current record's "edicao" value
 * @method Orcamento  setOrcamentos()       Sets the current record's "Orcamentos" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrcamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orcamento');
        $this->hasColumn('controle_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('responsavel', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subtotalGeral', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('subtotalMaterial', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('subtotalDiversos', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('subtotal20', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('subtotalPini', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('subtotalPiniBdi', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('total', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('anexo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('informacao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('observacao', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('usuario', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('data_hora', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('edicao', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Manutencao as Orcamentos', array(
             'local' => 'id',
             'foreign' => 'orcamento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}