<?php

/**
 * Basetipo_preventiva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $descricao
 * @property Doctrine_Collection $Tipo_preventivas
 * @property Doctrine_Collection $tipoP
 * @property Doctrine_Collection $vinculacao_tipo
 * @property Doctrine_Collection $cabecalho_preventivas
 * 
 * @method string              getNome()                  Returns the current record's "nome" value
 * @method string              getDescricao()             Returns the current record's "descricao" value
 * @method Doctrine_Collection getTipoPreventivas()       Returns the current record's "Tipo_preventivas" collection
 * @method Doctrine_Collection getTipoP()                 Returns the current record's "tipoP" collection
 * @method Doctrine_Collection getVinculacaoTipo()        Returns the current record's "vinculacao_tipo" collection
 * @method Doctrine_Collection getCabecalhoPreventivas()  Returns the current record's "cabecalho_preventivas" collection
 * @method tipo_preventiva     setNome()                  Sets the current record's "nome" value
 * @method tipo_preventiva     setDescricao()             Sets the current record's "descricao" value
 * @method tipo_preventiva     setTipoPreventivas()       Sets the current record's "Tipo_preventivas" collection
 * @method tipo_preventiva     setTipoP()                 Sets the current record's "tipoP" collection
 * @method tipo_preventiva     setVinculacaoTipo()        Sets the current record's "vinculacao_tipo" collection
 * @method tipo_preventiva     setCabecalhoPreventivas()  Sets the current record's "cabecalho_preventivas" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetipo_preventiva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_preventiva');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('servico_uf as Tipo_preventivas', array(
             'local' => 'id',
             'foreign' => 'tipo_preventiva_id'));

        $this->hasMany('tipo_preventiva_uf as tipoP', array(
             'local' => 'id',
             'foreign' => 'tipo_preventiva_id'));

        $this->hasMany('Vinculacao as vinculacao_tipo', array(
             'local' => 'id',
             'foreign' => 'tipo_preventiva_id'));

        $this->hasMany('cabecalho_tipo as cabecalho_preventivas', array(
             'local' => 'id',
             'foreign' => 'tipo_preventiva_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}