<?php

/**
 * Basesla_valores_totais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sla_id
 * @property integer $mes_id
 * @property integer $tipo_manutencao_id
 * @property decimal $percentual_multa_periodo
 * @property decimal $valor_da_multa
 * @property decimal $valor_multa_utilizado_extra_mensal
 * @property decimal $valor_multa_aplicada
 * @property decimal $indice_performance
 * @property sla_financeiro $sla_financeiro
 * @property meses_ano $meses_ano
 * @property preventiva_tipo $preventiva_tipo
 * 
 * @method integer            getSlaId()                              Returns the current record's "sla_id" value
 * @method integer            getMesId()                              Returns the current record's "mes_id" value
 * @method integer            getTipoManutencaoId()                   Returns the current record's "tipo_manutencao_id" value
 * @method decimal            getPercentualMultaPeriodo()             Returns the current record's "percentual_multa_periodo" value
 * @method decimal            getValorDaMulta()                       Returns the current record's "valor_da_multa" value
 * @method decimal            getValorMultaUtilizadoExtraMensal()     Returns the current record's "valor_multa_utilizado_extra_mensal" value
 * @method decimal            getValorMultaAplicada()                 Returns the current record's "valor_multa_aplicada" value
 * @method decimal            getIndicePerformance()                  Returns the current record's "indice_performance" value
 * @method sla_financeiro     getSlaFinanceiro()                      Returns the current record's "sla_financeiro" value
 * @method meses_ano          getMesesAno()                           Returns the current record's "meses_ano" value
 * @method preventiva_tipo    getPreventivaTipo()                     Returns the current record's "preventiva_tipo" value
 * @method sla_valores_totais setSlaId()                              Sets the current record's "sla_id" value
 * @method sla_valores_totais setMesId()                              Sets the current record's "mes_id" value
 * @method sla_valores_totais setTipoManutencaoId()                   Sets the current record's "tipo_manutencao_id" value
 * @method sla_valores_totais setPercentualMultaPeriodo()             Sets the current record's "percentual_multa_periodo" value
 * @method sla_valores_totais setValorDaMulta()                       Sets the current record's "valor_da_multa" value
 * @method sla_valores_totais setValorMultaUtilizadoExtraMensal()     Sets the current record's "valor_multa_utilizado_extra_mensal" value
 * @method sla_valores_totais setValorMultaAplicada()                 Sets the current record's "valor_multa_aplicada" value
 * @method sla_valores_totais setIndicePerformance()                  Sets the current record's "indice_performance" value
 * @method sla_valores_totais setSlaFinanceiro()                      Sets the current record's "sla_financeiro" value
 * @method sla_valores_totais setMesesAno()                           Sets the current record's "meses_ano" value
 * @method sla_valores_totais setPreventivaTipo()                     Sets the current record's "preventiva_tipo" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_valores_totais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla_valores_totais');
        $this->hasColumn('sla_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mes_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_manutencao_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('percentual_multa_periodo', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('valor_da_multa', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('valor_multa_utilizado_extra_mensal', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('valor_multa_aplicada', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('indice_performance', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sla_financeiro', array(
             'local' => 'sla_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('meses_ano', array(
             'local' => 'mes_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('preventiva_tipo', array(
             'local' => 'tipo_manutencao_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}