<?php

/**
 * Basefiscalizacao_item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $avaliacao
 * @property string $motivo
 * 
 * @method string            getAvaliacao() Returns the current record's "avaliacao" value
 * @method string            getMotivo()    Returns the current record's "motivo" value
 * @method fiscalizacao_item setAvaliacao() Sets the current record's "avaliacao" value
 * @method fiscalizacao_item setMotivo()    Sets the current record's "motivo" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefiscalizacao_item extends fiscalizacao_item_checklist
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('fiscalizacao_item');
        $this->hasColumn('avaliacao', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('motivo', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}