<?php

/**
 * BaseAfiliado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $empresa
 * @property string $email
 * @property string $token
 * @property boolean $ativado
 * @property Doctrine_Collection $Uf
 * @property Doctrine_Collection $Contract
 * @property Doctrine_Collection $Gram
 * @property Doctrine_Collection $sfGuardUfAfiliado
 * @property Doctrine_Collection $sfGuardContractAfiliado
 * @property Doctrine_Collection $sfGuardGramAfiliado
 * 
 * @method string              getEmpresa()                 Returns the current record's "empresa" value
 * @method string              getEmail()                   Returns the current record's "email" value
 * @method string              getToken()                   Returns the current record's "token" value
 * @method boolean             getAtivado()                 Returns the current record's "ativado" value
 * @method Doctrine_Collection getUf()                      Returns the current record's "Uf" collection
 * @method Doctrine_Collection getContract()                Returns the current record's "Contract" collection
 * @method Doctrine_Collection getGram()                    Returns the current record's "Gram" collection
 * @method Doctrine_Collection getSfGuardUfAfiliado()       Returns the current record's "sfGuardUfAfiliado" collection
 * @method Doctrine_Collection getSfGuardContractAfiliado() Returns the current record's "sfGuardContractAfiliado" collection
 * @method Doctrine_Collection getSfGuardGramAfiliado()     Returns the current record's "sfGuardGramAfiliado" collection
 * @method Afiliado            setEmpresa()                 Sets the current record's "empresa" value
 * @method Afiliado            setEmail()                   Sets the current record's "email" value
 * @method Afiliado            setToken()                   Sets the current record's "token" value
 * @method Afiliado            setAtivado()                 Sets the current record's "ativado" value
 * @method Afiliado            setUf()                      Sets the current record's "Uf" collection
 * @method Afiliado            setContract()                Sets the current record's "Contract" collection
 * @method Afiliado            setGram()                    Sets the current record's "Gram" collection
 * @method Afiliado            setSfGuardUfAfiliado()       Sets the current record's "sfGuardUfAfiliado" collection
 * @method Afiliado            setSfGuardContractAfiliado() Sets the current record's "sfGuardContractAfiliado" collection
 * @method Afiliado            setSfGuardGramAfiliado()     Sets the current record's "sfGuardGramAfiliado" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAfiliado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('afiliado');
        $this->hasColumn('empresa', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('ativado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUf as Uf', array(
             'refClass' => 'sfGuardUfAfiliado',
             'local' => 'afiliado_id',
             'foreign' => 'uf_id'));

        $this->hasMany('sfGuardContract as Contract', array(
             'refClass' => 'sfGuardContractAfiliado',
             'local' => 'afiliado_id',
             'foreign' => 'contract_id'));

        $this->hasMany('sfGuardGram as Gram', array(
             'refClass' => 'sfGuardGramAfiliado',
             'local' => 'afiliado_id',
             'foreign' => 'gram_id'));

        $this->hasMany('sfGuardUfAfiliado', array(
             'local' => 'id',
             'foreign' => 'afiliado_id'));

        $this->hasMany('sfGuardContractAfiliado', array(
             'local' => 'id',
             'foreign' => 'afiliado_id'));

        $this->hasMany('sfGuardGramAfiliado', array(
             'local' => 'id',
             'foreign' => 'afiliado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}