<?php

/**
 * Baseitem_fiscalizado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property Doctrine_Collection $Item_fiscalizados
 * @property Doctrine_Collection $fiscalizado_cabecalhos
 * 
 * @method string              getNome()                   Returns the current record's "nome" value
 * @method Doctrine_Collection getItemFiscalizados()       Returns the current record's "Item_fiscalizados" collection
 * @method Doctrine_Collection getFiscalizadoCabecalhos()  Returns the current record's "fiscalizado_cabecalhos" collection
 * @method item_fiscalizado    setNome()                   Sets the current record's "nome" value
 * @method item_fiscalizado    setItemFiscalizados()       Sets the current record's "Item_fiscalizados" collection
 * @method item_fiscalizado    setFiscalizadoCabecalhos()  Sets the current record's "fiscalizado_cabecalhos" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitem_fiscalizado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_fiscalizado');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('item_checklist as Item_fiscalizados', array(
             'local' => 'id',
             'foreign' => 'item_fiscalizado_id'));

        $this->hasMany('fiscalizado_cabecalho as fiscalizado_cabecalhos', array(
             'local' => 'id',
             'foreign' => 'item_fiscalizado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}