<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $avaliacao
 * @property string $correcao
 * @property string $irregularidade
 * 
 * @method string getAvaliacao()      Returns the current record's "avaliacao" value
 * @method string getCorrecao()       Returns the current record's "correcao" value
 * @method string getIrregularidade() Returns the current record's "irregularidade" value
 * @method Item   setAvaliacao()      Sets the current record's "avaliacao" value
 * @method Item   setCorrecao()       Sets the current record's "correcao" value
 * @method Item   setIrregularidade() Sets the current record's "irregularidade" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends item_checklist
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('item');
        $this->hasColumn('avaliacao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('correcao', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('irregularidade', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}