<?php

/**
 * BaseServico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $servico_id
 * @property string $tipo_de_servico
 * @property string $recurso_servico_requerido
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Servicos
 * 
 * @method string              getServicoId()                 Returns the current record's "servico_id" value
 * @method string              getTipoDeServico()             Returns the current record's "tipo_de_servico" value
 * @method string              getRecursoServicoRequerido()   Returns the current record's "recurso_servico_requerido" value
 * @method Doctrine_Collection getGroups()                    Returns the current record's "Groups" collection
 * @method Doctrine_Collection getServicos()                  Returns the current record's "Servicos" collection
 * @method Servico             setServicoId()                 Sets the current record's "servico_id" value
 * @method Servico             setTipoDeServico()             Sets the current record's "tipo_de_servico" value
 * @method Servico             setRecursoServicoRequerido()   Sets the current record's "recurso_servico_requerido" value
 * @method Servico             setGroups()                    Sets the current record's "Groups" collection
 * @method Servico             setServicos()                  Sets the current record's "Servicos" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servico');
        $this->hasColumn('servico_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo_de_servico', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('recurso_servico_requerido', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'servico_grupo',
             'local' => 'servico_id',
             'foreign' => 'group_id'));

        $this->hasMany('servico_grupo as Servicos', array(
             'local' => 'id',
             'foreign' => 'servico_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}