<?php

/**
 * Basesla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $conformidade_apurada
 * @property integer $item_sla
 * @property integer $quantidade_apurada
 * @property string $tipo
 * @property integer $fiscalizacao_item_cabecalho_id
 * @property integer $fiscalizacao_id
 * @property fiscalizacao_item_cabecalho $fiscalizacao_item_cabecalho
 * 
 * @method string                      getConformidadeApurada()            Returns the current record's "conformidade_apurada" value
 * @method integer                     getItemSla()                        Returns the current record's "item_sla" value
 * @method integer                     getQuantidadeApurada()              Returns the current record's "quantidade_apurada" value
 * @method string                      getTipo()                           Returns the current record's "tipo" value
 * @method integer                     getFiscalizacaoItemCabecalhoId()    Returns the current record's "fiscalizacao_item_cabecalho_id" value
 * @method integer                     getFiscalizacaoId()                 Returns the current record's "fiscalizacao_id" value
 * @method fiscalizacao_item_cabecalho getFiscalizacaoItemCabecalho()      Returns the current record's "fiscalizacao_item_cabecalho" value
 * @method sla                         setConformidadeApurada()            Sets the current record's "conformidade_apurada" value
 * @method sla                         setItemSla()                        Sets the current record's "item_sla" value
 * @method sla                         setQuantidadeApurada()              Sets the current record's "quantidade_apurada" value
 * @method sla                         setTipo()                           Sets the current record's "tipo" value
 * @method sla                         setFiscalizacaoItemCabecalhoId()    Sets the current record's "fiscalizacao_item_cabecalho_id" value
 * @method sla                         setFiscalizacaoId()                 Sets the current record's "fiscalizacao_id" value
 * @method sla                         setFiscalizacaoItemCabecalho()      Sets the current record's "fiscalizacao_item_cabecalho" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla');
        $this->hasColumn('conformidade_apurada', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('item_sla', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quantidade_apurada', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('fiscalizacao_item_cabecalho_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fiscalizacao_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('fiscalizacao_item_cabecalho', array(
             'local' => 'fiscalizacao_item_cabecalho_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}