<?php

/**
 * Basesla_apuracao_manutencao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_apuracao_manutencao extends sla_apuracao
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('sla_apuracao_manutencao');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}