<?php

/**
 * BaseManutencao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $status
 * @property string $justificativa_status
 * @property integer $orcamento_id
 * @property Orcamento $Orcamento
 * 
 * @method string     getStatus()               Returns the current record's "status" value
 * @method string     getJustificativaStatus()  Returns the current record's "justificativa_status" value
 * @method integer    getOrcamentoId()          Returns the current record's "orcamento_id" value
 * @method Orcamento  getOrcamento()            Returns the current record's "Orcamento" value
 * @method Manutencao setStatus()               Sets the current record's "status" value
 * @method Manutencao setJustificativaStatus()  Sets the current record's "justificativa_status" value
 * @method Manutencao setOrcamentoId()          Sets the current record's "orcamento_id" value
 * @method Manutencao setOrcamento()            Sets the current record's "Orcamento" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManutencao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('manutencao');
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Em análise pelo fornecedor',
             'length' => 255,
             ));
        $this->hasColumn('justificativa_status', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('orcamento_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Orcamento', array(
             'local' => 'orcamento_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}