<?php

/**
 * Baseitem_cabecalho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property integer $tipo_avaliacao_id
 * @property integer $cabecalho_id
 * @property tipo_avaliacao $tipo_avaliacao
 * @property Cabecalho $Cabecalho
 * @property Doctrine_Collection $Itens
 * 
 * @method string              getNome()              Returns the current record's "nome" value
 * @method integer             getTipoAvaliacaoId()   Returns the current record's "tipo_avaliacao_id" value
 * @method integer             getCabecalhoId()       Returns the current record's "cabecalho_id" value
 * @method tipo_avaliacao      getTipoAvaliacao()     Returns the current record's "tipo_avaliacao" value
 * @method Cabecalho           getCabecalho()         Returns the current record's "Cabecalho" value
 * @method Doctrine_Collection getItens()             Returns the current record's "Itens" collection
 * @method item_cabecalho      setNome()              Sets the current record's "nome" value
 * @method item_cabecalho      setTipoAvaliacaoId()   Sets the current record's "tipo_avaliacao_id" value
 * @method item_cabecalho      setCabecalhoId()       Sets the current record's "cabecalho_id" value
 * @method item_cabecalho      setTipoAvaliacao()     Sets the current record's "tipo_avaliacao" value
 * @method item_cabecalho      setCabecalho()         Sets the current record's "Cabecalho" value
 * @method item_cabecalho      setItens()             Sets the current record's "Itens" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitem_cabecalho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_cabecalho');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo_avaliacao_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cabecalho_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tipo_avaliacao', array(
             'local' => 'tipo_avaliacao_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Cabecalho', array(
             'local' => 'cabecalho_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('item_checklist as Itens', array(
             'local' => 'id',
             'foreign' => 'item_cabecalho_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}