<?php

/**
 * BaseChecklist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property datetime $data_de_execucao_inicio
 * @property datetime $data_de_execucao
 * @property string $relatorio_fotografico_link
 * @property string $relatorio_fotografico_pdf
 * @property integer $user_id
 * @property integer $corretiva_id
 * @property string $observacao
 * @property boolean $preventiva_realizada
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Checklists
 * @property Doctrine_Collection $preventiva_checklists
 * 
 * @method datetime            getDataDeExecucaoInicio()       Returns the current record's "data_de_execucao_inicio" value
 * @method datetime            getDataDeExecucao()             Returns the current record's "data_de_execucao" value
 * @method string              getRelatorioFotograficoLink()   Returns the current record's "relatorio_fotografico_link" value
 * @method string              getRelatorioFotograficoPdf()    Returns the current record's "relatorio_fotografico_pdf" value
 * @method integer             getUserId()                     Returns the current record's "user_id" value
 * @method integer             getCorretivaId()                Returns the current record's "corretiva_id" value
 * @method string              getObservacao()                 Returns the current record's "observacao" value
 * @method boolean             getPreventivaRealizada()        Returns the current record's "preventiva_realizada" value
 * @method sfGuardUser         getSfGuardUser()                Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getChecklists()                 Returns the current record's "Checklists" collection
 * @method Doctrine_Collection getPreventivaChecklists()       Returns the current record's "preventiva_checklists" collection
 * @method Checklist           setDataDeExecucaoInicio()       Sets the current record's "data_de_execucao_inicio" value
 * @method Checklist           setDataDeExecucao()             Sets the current record's "data_de_execucao" value
 * @method Checklist           setRelatorioFotograficoLink()   Sets the current record's "relatorio_fotografico_link" value
 * @method Checklist           setRelatorioFotograficoPdf()    Sets the current record's "relatorio_fotografico_pdf" value
 * @method Checklist           setUserId()                     Sets the current record's "user_id" value
 * @method Checklist           setCorretivaId()                Sets the current record's "corretiva_id" value
 * @method Checklist           setObservacao()                 Sets the current record's "observacao" value
 * @method Checklist           setPreventivaRealizada()        Sets the current record's "preventiva_realizada" value
 * @method Checklist           setSfGuardUser()                Sets the current record's "sfGuardUser" value
 * @method Checklist           setChecklists()                 Sets the current record's "Checklists" collection
 * @method Checklist           setPreventivaChecklists()       Sets the current record's "preventiva_checklists" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChecklist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('checklist');
        $this->hasColumn('data_de_execucao_inicio', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('data_de_execucao', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('relatorio_fotografico_link', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('relatorio_fotografico_pdf', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('corretiva_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('observacao', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('preventiva_realizada', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('item_checklist as Checklists', array(
             'local' => 'id',
             'foreign' => 'checklist_id'));

        $this->hasMany('Preventiva as preventiva_checklists', array(
             'local' => 'id',
             'foreign' => 'checklist_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}