<?php

/**
 * BasePini_item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $orcamento_id
 * @property string $codigo
 * @property string $descricao
 * @property string $classe
 * @property string $unidade
 * @property decimal $quantidade
 * @property decimal $valor_unitario
 * @property decimal $valor_total
 * @property Orcamento $Orcamento
 * 
 * @method integer   getOrcamentoId()    Returns the current record's "orcamento_id" value
 * @method string    getCodigo()         Returns the current record's "codigo" value
 * @method string    getDescricao()      Returns the current record's "descricao" value
 * @method string    getClasse()         Returns the current record's "classe" value
 * @method string    getUnidade()        Returns the current record's "unidade" value
 * @method decimal   getQuantidade()     Returns the current record's "quantidade" value
 * @method decimal   getValorUnitario()  Returns the current record's "valor_unitario" value
 * @method decimal   getValorTotal()     Returns the current record's "valor_total" value
 * @method Orcamento getOrcamento()      Returns the current record's "Orcamento" value
 * @method Pini_item setOrcamentoId()    Sets the current record's "orcamento_id" value
 * @method Pini_item setCodigo()         Sets the current record's "codigo" value
 * @method Pini_item setDescricao()      Sets the current record's "descricao" value
 * @method Pini_item setClasse()         Sets the current record's "classe" value
 * @method Pini_item setUnidade()        Sets the current record's "unidade" value
 * @method Pini_item setQuantidade()     Sets the current record's "quantidade" value
 * @method Pini_item setValorUnitario()  Sets the current record's "valor_unitario" value
 * @method Pini_item setValorTotal()     Sets the current record's "valor_total" value
 * @method Pini_item setOrcamento()      Sets the current record's "Orcamento" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePini_item extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pini_item');
        $this->hasColumn('orcamento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('classe', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('unidade', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('quantidade', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('valor_unitario', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('valor_total', 'decimal', null, array(
             'type' => 'decimal',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Orcamento', array(
             'local' => 'orcamento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}