<?php

/**
 * Baseservico_grupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $servico_id
 * @property integer $group_id
 * @property Servico $Servico
 * @property sfGuardGroup $sfGuardGroup
 * 
 * @method integer       getServicoId()    Returns the current record's "servico_id" value
 * @method integer       getGroupId()      Returns the current record's "group_id" value
 * @method Servico       getServico()      Returns the current record's "Servico" value
 * @method sfGuardGroup  getSfGuardGroup() Returns the current record's "sfGuardGroup" value
 * @method servico_grupo setServicoId()    Sets the current record's "servico_id" value
 * @method servico_grupo setGroupId()      Sets the current record's "group_id" value
 * @method servico_grupo setServico()      Sets the current record's "Servico" value
 * @method servico_grupo setSfGuardGroup() Sets the current record's "sfGuardGroup" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseservico_grupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servico_grupo');
        $this->hasColumn('servico_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Servico', array(
             'local' => 'servico_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}