<?php

/**
 * BaseTelegram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $chat_id
 * @property string $token
 * @property Doctrine_Collection $Telegram
 * 
 * @method string              getChatId()   Returns the current record's "chat_id" value
 * @method string              getToken()    Returns the current record's "token" value
 * @method Doctrine_Collection getTelegram() Returns the current record's "Telegram" collection
 * @method Telegram            setChatId()   Sets the current record's "chat_id" value
 * @method Telegram            setToken()    Sets the current record's "token" value
 * @method Telegram            setTelegram() Sets the current record's "Telegram" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTelegram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('telegram');
        $this->hasColumn('chat_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGram as Telegram', array(
             'local' => 'id',
             'foreign' => 'telegram_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}