<?php

/**
 * Basemeses_ano
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $sigla
 * @property Doctrine_Collection $mesApuracao
 * @property Doctrine_Collection $mesEvidencia
 * @property Doctrine_Collection $mesValor
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getSigla()        Returns the current record's "sigla" value
 * @method Doctrine_Collection getMesApuracao()  Returns the current record's "mesApuracao" collection
 * @method Doctrine_Collection getMesEvidencia() Returns the current record's "mesEvidencia" collection
 * @method Doctrine_Collection getMesValor()     Returns the current record's "mesValor" collection
 * @method meses_ano           setName()         Sets the current record's "name" value
 * @method meses_ano           setSigla()        Sets the current record's "sigla" value
 * @method meses_ano           setMesApuracao()  Sets the current record's "mesApuracao" collection
 * @method meses_ano           setMesEvidencia() Sets the current record's "mesEvidencia" collection
 * @method meses_ano           setMesValor()     Sets the current record's "mesValor" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemeses_ano extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meses_ano');
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('sigla', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sla_apuracao as mesApuracao', array(
             'local' => 'id',
             'foreign' => 'mes_referencia'));

        $this->hasMany('sla_evidencia as mesEvidencia', array(
             'local' => 'id',
             'foreign' => 'mes_referencia'));

        $this->hasMany('sla_valores_totais as mesValor', array(
             'local' => 'id',
             'foreign' => 'mes_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}