<?php

/**
 * BasePreventiva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $periodicidade_id
 * @property integer $ciclo_id
 * @property datetime $ultima_preventiva
 * @property date $data_programada_fixa
 * @property date $data_programada
 * @property integer $checklist_id
 * @property integer $preventiva_tipo_id
 * @property integer $base_predial_id
 * @property integer $pendencia_id
 * @property Periodicidade $Periodicidade
 * @property Ciclo $Ciclo
 * @property Checklist $Checklist
 * @property preventiva_tipo $preventiva_tipo
 * @property base_predial $base_predial
 * @property Pendencia $Pendencia
 * @property Doctrine_Collection $preventiva_pai
 * @property Doctrine_Collection $preventiva_filho
 * 
 * @method integer             getPeriodicidadeId()      Returns the current record's "periodicidade_id" value
 * @method integer             getCicloId()              Returns the current record's "ciclo_id" value
 * @method datetime            getUltimaPreventiva()     Returns the current record's "ultima_preventiva" value
 * @method date                getDataProgramadaFixa()   Returns the current record's "data_programada_fixa" value
 * @method date                getDataProgramada()       Returns the current record's "data_programada" value
 * @method integer             getChecklistId()          Returns the current record's "checklist_id" value
 * @method integer             getPreventivaTipoId()     Returns the current record's "preventiva_tipo_id" value
 * @method integer             getBasePredialId()        Returns the current record's "base_predial_id" value
 * @method integer             getPendenciaId()          Returns the current record's "pendencia_id" value
 * @method Periodicidade       getPeriodicidade()        Returns the current record's "Periodicidade" value
 * @method Ciclo               getCiclo()                Returns the current record's "Ciclo" value
 * @method Checklist           getChecklist()            Returns the current record's "Checklist" value
 * @method preventiva_tipo     getPreventivaTipo()       Returns the current record's "preventiva_tipo" value
 * @method base_predial        getBasePredial()          Returns the current record's "base_predial" value
 * @method Pendencia           getPendencia()            Returns the current record's "Pendencia" value
 * @method Doctrine_Collection getPreventivaPai()        Returns the current record's "preventiva_pai" collection
 * @method Doctrine_Collection getPreventivaFilho()      Returns the current record's "preventiva_filho" collection
 * @method Preventiva          setPeriodicidadeId()      Sets the current record's "periodicidade_id" value
 * @method Preventiva          setCicloId()              Sets the current record's "ciclo_id" value
 * @method Preventiva          setUltimaPreventiva()     Sets the current record's "ultima_preventiva" value
 * @method Preventiva          setDataProgramadaFixa()   Sets the current record's "data_programada_fixa" value
 * @method Preventiva          setDataProgramada()       Sets the current record's "data_programada" value
 * @method Preventiva          setChecklistId()          Sets the current record's "checklist_id" value
 * @method Preventiva          setPreventivaTipoId()     Sets the current record's "preventiva_tipo_id" value
 * @method Preventiva          setBasePredialId()        Sets the current record's "base_predial_id" value
 * @method Preventiva          setPendenciaId()          Sets the current record's "pendencia_id" value
 * @method Preventiva          setPeriodicidade()        Sets the current record's "Periodicidade" value
 * @method Preventiva          setCiclo()                Sets the current record's "Ciclo" value
 * @method Preventiva          setChecklist()            Sets the current record's "Checklist" value
 * @method Preventiva          setPreventivaTipo()       Sets the current record's "preventiva_tipo" value
 * @method Preventiva          setBasePredial()          Sets the current record's "base_predial" value
 * @method Preventiva          setPendencia()            Sets the current record's "Pendencia" value
 * @method Preventiva          setPreventivaPai()        Sets the current record's "preventiva_pai" collection
 * @method Preventiva          setPreventivaFilho()      Sets the current record's "preventiva_filho" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePreventiva extends Manutencao
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('preventiva');
        $this->hasColumn('periodicidade_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ciclo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ultima_preventiva', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => false,
             ));
        $this->hasColumn('data_programada_fixa', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('data_programada', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('checklist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('preventiva_tipo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('base_predial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pendencia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Periodicidade', array(
             'local' => 'periodicidade_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Ciclo', array(
             'local' => 'ciclo_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Checklist', array(
             'local' => 'checklist_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('preventiva_tipo', array(
             'local' => 'preventiva_tipo_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('base_predial', array(
             'local' => 'base_predial_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Pendencia', array(
             'local' => 'pendencia_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Vinculacao as preventiva_pai', array(
             'local' => 'id',
             'foreign' => 'preventiva_pai'));

        $this->hasMany('Vinculacao as preventiva_filho', array(
             'local' => 'id',
             'foreign' => 'preventiva_filho'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}