<?php

/**
 * Basepreco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $valor
 * @property integer $pini_id
 * @property integer $uf_id
 * @property Pini $Pini
 * @property sfGuardUf $sfGuardUf
 * 
 * @method decimal   getValor()     Returns the current record's "valor" value
 * @method integer   getPiniId()    Returns the current record's "pini_id" value
 * @method integer   getUfId()      Returns the current record's "uf_id" value
 * @method Pini      getPini()      Returns the current record's "Pini" value
 * @method sfGuardUf getSfGuardUf() Returns the current record's "sfGuardUf" value
 * @method preco     setValor()     Sets the current record's "valor" value
 * @method preco     setPiniId()    Sets the current record's "pini_id" value
 * @method preco     setUfId()      Sets the current record's "uf_id" value
 * @method preco     setPini()      Sets the current record's "Pini" value
 * @method preco     setSfGuardUf() Sets the current record's "sfGuardUf" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepreco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preco');
        $this->hasColumn('valor', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('pini_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('uf_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pini', array(
             'local' => 'pini_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUf', array(
             'local' => 'uf_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}