<?php

/**
 * Basetipo_preventiva_uf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tipo_preventiva_id
 * @property integer $uf_id
 * @property tipo_preventiva $tipo_preventiva
 * @property sfGuardUf $sfGuardUf
 * 
 * @method integer            getTipoPreventivaId()   Returns the current record's "tipo_preventiva_id" value
 * @method integer            getUfId()               Returns the current record's "uf_id" value
 * @method tipo_preventiva    getTipoPreventiva()     Returns the current record's "tipo_preventiva" value
 * @method sfGuardUf          getSfGuardUf()          Returns the current record's "sfGuardUf" value
 * @method tipo_preventiva_uf setTipoPreventivaId()   Sets the current record's "tipo_preventiva_id" value
 * @method tipo_preventiva_uf setUfId()               Sets the current record's "uf_id" value
 * @method tipo_preventiva_uf setTipoPreventiva()     Sets the current record's "tipo_preventiva" value
 * @method tipo_preventiva_uf setSfGuardUf()          Sets the current record's "sfGuardUf" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetipo_preventiva_uf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_preventiva_uf');
        $this->hasColumn('tipo_preventiva_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('uf_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 13,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tipo_preventiva', array(
             'local' => 'tipo_preventiva_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUf', array(
             'local' => 'uf_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}