<?php

/**
 * BasePendencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $checklist_pendenciado
 * @property boolean $relatorio_fotografico_pendenciado
 * @property boolean $orcamento_pendenciado
 * @property integer $num_pendencias
 * @property Preventiva $Pendencias
 * 
 * @method boolean    getChecklistPendenciado()              Returns the current record's "checklist_pendenciado" value
 * @method boolean    getRelatorioFotograficoPendenciado()   Returns the current record's "relatorio_fotografico_pendenciado" value
 * @method boolean    getOrcamentoPendenciado()              Returns the current record's "orcamento_pendenciado" value
 * @method integer    getNumPendencias()                     Returns the current record's "num_pendencias" value
 * @method Preventiva getPendencias()                        Returns the current record's "Pendencias" value
 * @method Pendencia  setChecklistPendenciado()              Sets the current record's "checklist_pendenciado" value
 * @method Pendencia  setRelatorioFotograficoPendenciado()   Sets the current record's "relatorio_fotografico_pendenciado" value
 * @method Pendencia  setOrcamentoPendenciado()              Sets the current record's "orcamento_pendenciado" value
 * @method Pendencia  setNumPendencias()                     Sets the current record's "num_pendencias" value
 * @method Pendencia  setPendencias()                        Sets the current record's "Pendencias" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePendencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pendencia');
        $this->hasColumn('checklist_pendenciado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('relatorio_fotografico_pendenciado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('orcamento_pendenciado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('num_pendencias', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Preventiva as Pendencias', array(
             'local' => 'id',
             'foreign' => 'pendencia_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}