<?php

/**
 * BaseVinculacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $preventiva_pai
 * @property integer $preventiva_filho
 * @property Preventiva $Preventiva
 * 
 * @method integer    getPreventivaPai()    Returns the current record's "preventiva_pai" value
 * @method integer    getPreventivaFilho()  Returns the current record's "preventiva_filho" value
 * @method Preventiva getPreventivaPai()    Returns the current record's "Preventiva_pai" value
 * @method Preventiva getPreventiva()       Returns the current record's "Preventiva" value
 * @method Vinculacao setPreventivaPai()    Sets the current record's "preventiva_pai" value
 * @method Vinculacao setPreventivaFilho()  Sets the current record's "preventiva_filho" value
 * @method Vinculacao setPreventivaPai()    Sets the current record's "Preventiva_pai" value
 * @method Vinculacao setPreventiva()       Sets the current record's "Preventiva" value_pai
 * @property Preventiva $Preventiva
 * 
 * @method integer    getPreventivaPai()    Returns the current record's "preventiva_pai" value
 * @method integer    getPreventivaFilho()  Returns the current record's "preventiva_filho" value
 * @method Preventiva getPreventivaPai()    Returns the current record's "Preventiva_pai" value
 * @method Preventiva getPreventiva()       Returns the current record's "Preventiva" value
 * @method Vinculacao setPreventivaPai()    Sets the current record's "preventiva_pai" value
 * @method Vinculacao setPreventivaFilho()  Sets the current record's "preventiva_filho" value
 * @method Vinculacao setPreventivaPai()    Sets the current record's "Preventiva_pai" value
 * @method Vinculacao setPreventiva()       Sets the current record's "Preventiva" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVinculacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vinculacao');
        $this->hasColumn('preventiva_pai', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('preventiva_filho', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Preventiva as Preventiva_pai', array(
             'local' => 'preventiva_pai',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Preventiva', array(
             'local' => 'preventiva_filho',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}