<?php

/**
 * BasePini
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cod_pini
 * @property string $descricao
 * @property string $classe
 * @property string $unidade
 * @property Doctrine_Collection $PiniPreco
 * 
 * @method string              getCodPini()   Returns the current record's "cod_pini" value
 * @method string              getDescricao() Returns the current record's "descricao" value
 * @method string              getClasse()    Returns the current record's "classe" value
 * @method string              getUnidade()   Returns the current record's "unidade" value
 * @method Doctrine_Collection getPiniPreco() Returns the current record's "PiniPreco" collection
 * @method Pini                setCodPini()   Sets the current record's "cod_pini" value
 * @method Pini                setDescricao() Sets the current record's "descricao" value
 * @method Pini                setClasse()    Sets the current record's "classe" value
 * @method Pini                setUnidade()   Sets the current record's "unidade" value
 * @method Pini                setPiniPreco() Sets the current record's "PiniPreco" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePini extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pini');
        $this->hasColumn('cod_pini', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('classe', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('unidade', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('preco as PiniPreco', array(
             'local' => 'id',
             'foreign' => 'pini_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}