<?php

/**
 * Basesla_cabecalho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property integer $tipo_manutencao_id
 * @property decimal $deducao
 * @property string $texto_pontuacao
 * @property string $texto_calculo
 * @property preventiva_tipo $preventiva_tipo
 * @property Doctrine_Collection $pais
 * @property Doctrine_Collection $SlaItemApuracao
 * @property Doctrine_Collection $SlaItemEvidencia
 * 
 * @method string              getNome()               Returns the current record's "nome" value
 * @method integer             getTipoManutencaoId()   Returns the current record's "tipo_manutencao_id" value
 * @method decimal             getDeducao()            Returns the current record's "deducao" value
 * @method string              getTextoPontuacao()     Returns the current record's "texto_pontuacao" value
 * @method string              getTextoCalculo()       Returns the current record's "texto_calculo" value
 * @method preventiva_tipo     getPreventivaTipo()     Returns the current record's "preventiva_tipo" value
 * @method Doctrine_Collection getPais()               Returns the current record's "pais" collection
 * @method Doctrine_Collection getSlaItemApuracao()    Returns the current record's "SlaItemApuracao" collection
 * @method Doctrine_Collection getSlaItemEvidencia()   Returns the current record's "SlaItemEvidencia" collection
 * @method sla_cabecalho       setNome()               Sets the current record's "nome" value
 * @method sla_cabecalho       setTipoManutencaoId()   Sets the current record's "tipo_manutencao_id" value
 * @method sla_cabecalho       setDeducao()            Sets the current record's "deducao" value
 * @method sla_cabecalho       setTextoPontuacao()     Sets the current record's "texto_pontuacao" value
 * @method sla_cabecalho       setTextoCalculo()       Sets the current record's "texto_calculo" value
 * @method sla_cabecalho       setPreventivaTipo()     Sets the current record's "preventiva_tipo" value
 * @method sla_cabecalho       setPais()               Sets the current record's "pais" collection
 * @method sla_cabecalho       setSlaItemApuracao()    Sets the current record's "SlaItemApuracao" collection
 * @method sla_cabecalho       setSlaItemEvidencia()   Sets the current record's "SlaItemEvidencia" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_cabecalho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla_cabecalho');
        $this->hasColumn('nome', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
        $this->hasColumn('tipo_manutencao_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('deducao', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('texto_pontuacao', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('texto_calculo', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('preventiva_tipo', array(
             'local' => 'tipo_manutencao_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('sla_item_cabecalho as pais', array(
             'local' => 'id',
             'foreign' => 'cabecalho_pai'));

        $this->hasMany('sla_apuracao as SlaItemApuracao', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('sla_evidencia as SlaItemEvidencia', array(
             'local' => 'id',
             'foreign' => 'item_sla_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}