<?php

/**
 * Baselpu_servico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * @property string $especificacao
 * @property string $unidade
 * @property decimal $valor
 * @property string $estado
 * 
 * @method string      getCodigo()        Returns the current record's "codigo" value
 * @method string      getEspecificacao() Returns the current record's "especificacao" value
 * @method string      getUnidade()       Returns the current record's "unidade" value
 * @method decimal     getValor()         Returns the current record's "valor" value
 * @method string      getEstado()        Returns the current record's "estado" value
 * @method lpu_servico setCodigo()        Sets the current record's "codigo" value
 * @method lpu_servico setEspecificacao() Sets the current record's "especificacao" value
 * @method lpu_servico setUnidade()       Sets the current record's "unidade" value
 * @method lpu_servico setValor()         Sets the current record's "valor" value
 * @method lpu_servico setEstado()        Sets the current record's "estado" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselpu_servico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lpu_servico');
        $this->hasColumn('codigo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('especificacao', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('unidade', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('valor', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('estado', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}