<?php

/**
 * Basesla_financeiro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $filial_id
 * @property integer $fornecedor_id
 * @property integer $ano
 * @property integer $fop_responsavel_id
 * @property fornecedor $fornecedor
 * @property sfGuardUser $sfGuardUser
 * @property sfGuardUf $sfGuardUf
 * @property Doctrine_Collection $SlaApuracao
 * @property Doctrine_Collection $SlaEvidencia
 * @property Doctrine_Collection $SlaValores
 * 
 * @method integer             getFilialId()           Returns the current record's "filial_id" value
 * @method integer             getFornecedorId()       Returns the current record's "fornecedor_id" value
 * @method integer             getAno()                Returns the current record's "ano" value
 * @method integer             getFopResponsavelId()   Returns the current record's "fop_responsavel_id" value
 * @method fornecedor          getFornecedor()         Returns the current record's "fornecedor" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method sfGuardUf           getSfGuardUf()          Returns the current record's "sfGuardUf" value
 * @method Doctrine_Collection getSlaApuracao()        Returns the current record's "SlaApuracao" collection
 * @method Doctrine_Collection getSlaEvidencia()       Returns the current record's "SlaEvidencia" collection
 * @method Doctrine_Collection getSlaValores()         Returns the current record's "SlaValores" collection
 * @method sla_financeiro      setFilialId()           Sets the current record's "filial_id" value
 * @method sla_financeiro      setFornecedorId()       Sets the current record's "fornecedor_id" value
 * @method sla_financeiro      setAno()                Sets the current record's "ano" value
 * @method sla_financeiro      setFopResponsavelId()   Sets the current record's "fop_responsavel_id" value
 * @method sla_financeiro      setFornecedor()         Sets the current record's "fornecedor" value
 * @method sla_financeiro      setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method sla_financeiro      setSfGuardUf()          Sets the current record's "sfGuardUf" value
 * @method sla_financeiro      setSlaApuracao()        Sets the current record's "SlaApuracao" collection
 * @method sla_financeiro      setSlaEvidencia()       Sets the current record's "SlaEvidencia" collection
 * @method sla_financeiro      setSlaValores()         Sets the current record's "SlaValores" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_financeiro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla_financeiro');
        $this->hasColumn('filial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fornecedor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ano', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fop_responsavel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('fornecedor', array(
             'local' => 'fornecedor_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'fop_responsavel_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sfGuardUf', array(
             'local' => 'filial_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('sla_apuracao as SlaApuracao', array(
             'local' => 'id',
             'foreign' => 'sla_id'));

        $this->hasMany('sla_evidencia as SlaEvidencia', array(
             'local' => 'id',
             'foreign' => 'sla_id'));

        $this->hasMany('sla_valores_totais as SlaValores', array(
             'local' => 'id',
             'foreign' => 'sla_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}