<?php

/**
 * BaseChamado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $email
 * @property string $celular
 * @property string $estado
 * @property string $sigla_da_estacao
 * @property string $gram
 * @property string $gram_atendimento
 * @property string $cidade
 * @property string $endereco
 * @property string $contrato
 * @property string $complemento
 * @property string $tipo_de_servico
 * @property string $recurso_servico_requerido
 * @property integer $stme
 * @property string $justificativa
 * @property string $anexos
 * @property integer $pesquisa_satisfacao_id
 * @property string $unique_key
 * @property string $solicitante
 * @property string $contato
 * @property string $prioridade
 * @property boolean $aberto_como_emergencial
 * @property datetime $data_de_execucao
 * @property datetime $data_programada
 * @property datetime $data_contato_cliente
 * @property string $relatorio_fotografico
 * @property integer $os
 * @property pesquisa_satisfacao $pesquisa_satisfacao
 * 
 * @method string              getNome()                      Returns the current record's "nome" value
 * @method string              getEmail()                     Returns the current record's "email" value
 * @method string              getCelular()                   Returns the current record's "celular" value
 * @method string              getEstado()                    Returns the current record's "estado" value
 * @method string              getSiglaDaEstacao()            Returns the current record's "sigla_da_estacao" value
 * @method string              getGram()                      Returns the current record's "gram" value
 * @method string              getGramAtendimento()           Returns the current record's "gram_atendimento" value
 * @method string              getCidade()                    Returns the current record's "cidade" value
 * @method string              getEndereco()                  Returns the current record's "endereco" value
 * @method string              getContrato()                  Returns the current record's "contrato" value
 * @method string              getComplemento()               Returns the current record's "complemento" value
 * @method string              getTipoDeServico()             Returns the current record's "tipo_de_servico" value
 * @method string              getRecursoServicoRequerido()   Returns the current record's "recurso_servico_requerido" value
 * @method integer             getStme()                      Returns the current record's "stme" value
 * @method string              getJustificativa()             Returns the current record's "justificativa" value
 * @method string              getAnexos()                    Returns the current record's "anexos" value
 * @method integer             getPesquisaSatisfacaoId()      Returns the current record's "pesquisa_satisfacao_id" value
 * @method string              getUniqueKey()                 Returns the current record's "unique_key" value
 * @method string              getSolicitante()               Returns the current record's "solicitante" value
 * @method string              getContato()                   Returns the current record's "contato" value
 * @method string              getPrioridade()                Returns the current record's "prioridade" value
 * @method boolean             getAbertoComoEmergencial()     Returns the current record's "aberto_como_emergencial" value
 * @method datetime            getDataDeExecucao()            Returns the current record's "data_de_execucao" value
 * @method datetime            getDataProgramada()            Returns the current record's "data_programada" value
 * @method datetime            getDataContatoCliente()        Returns the current record's "data_contato_cliente" value
 * @method string              getRelatorioFotografico()      Returns the current record's "relatorio_fotografico" value
 * @method integer             getOs()                        Returns the current record's "os" value
 * @method pesquisa_satisfacao getPesquisaSatisfacao()        Returns the current record's "pesquisa_satisfacao" value
 * @method Chamado             setNome()                      Sets the current record's "nome" value
 * @method Chamado             setEmail()                     Sets the current record's "email" value
 * @method Chamado             setCelular()                   Sets the current record's "celular" value
 * @method Chamado             setEstado()                    Sets the current record's "estado" value
 * @method Chamado             setSiglaDaEstacao()            Sets the current record's "sigla_da_estacao" value
 * @method Chamado             setGram()                      Sets the current record's "gram" value
 * @method Chamado             setGramAtendimento()           Sets the current record's "gram_atendimento" value
 * @method Chamado             setCidade()                    Sets the current record's "cidade" value
 * @method Chamado             setEndereco()                  Sets the current record's "endereco" value
 * @method Chamado             setContrato()                  Sets the current record's "contrato" value
 * @method Chamado             setComplemento()               Sets the current record's "complemento" value
 * @method Chamado             setTipoDeServico()             Sets the current record's "tipo_de_servico" value
 * @method Chamado             setRecursoServicoRequerido()   Sets the current record's "recurso_servico_requerido" value
 * @method Chamado             setStme()                      Sets the current record's "stme" value
 * @method Chamado             setJustificativa()             Sets the current record's "justificativa" value
 * @method Chamado             setAnexos()                    Sets the current record's "anexos" value
 * @method Chamado             setPesquisaSatisfacaoId()      Sets the current record's "pesquisa_satisfacao_id" value
 * @method Chamado             setUniqueKey()                 Sets the current record's "unique_key" value
 * @method Chamado             setSolicitante()               Sets the current record's "solicitante" value
 * @method Chamado             setContato()                   Sets the current record's "contato" value
 * @method Chamado             setPrioridade()                Sets the current record's "prioridade" value
 * @method Chamado             setAbertoComoEmergencial()     Sets the current record's "aberto_como_emergencial" value
 * @method Chamado             setDataDeExecucao()            Sets the current record's "data_de_execucao" value
 * @method Chamado             setDataProgramada()            Sets the current record's "data_programada" value
 * @method Chamado             setDataContatoCliente()        Sets the current record's "data_contato_cliente" value
 * @method Chamado             setRelatorioFotografico()      Sets the current record's "relatorio_fotografico" value
 * @method Chamado             setOs()                        Sets the current record's "os" value
 * @method Chamado             setPesquisaSatisfacao()        Sets the current record's "pesquisa_satisfacao" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChamado extends Manutencao
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('chamado');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('celular', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('estado', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('sigla_da_estacao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('gram', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('gram_atendimento', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cidade', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('endereco', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('contrato', 'string', 255, array(
             'type' => 'string',
             'default' => 'operacional',
             'length' => 255,
             ));
        $this->hasColumn('complemento', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tipo_de_servico', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('recurso_servico_requerido', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('stme', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('justificativa', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('anexos', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pesquisa_satisfacao_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('unique_key', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('solicitante', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('contato', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('prioridade', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('aberto_como_emergencial', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('data_de_execucao', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('data_programada', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('data_contato_cliente', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('relatorio_fotografico', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('os', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('pesquisa_satisfacao', array(
             'local' => 'pesquisa_satisfacao_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}