<?php

/**
 * Basetipo_avaliacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tipo
 * @property string $criterio
 * @property Doctrine_Collection $Tipos_avaliacao
 * 
 * @method string              getTipo()            Returns the current record's "tipo" value
 * @method string              getCriterio()        Returns the current record's "criterio" value
 * @method Doctrine_Collection getTiposAvaliacao()  Returns the current record's "Tipos_avaliacao" collection
 * @method tipo_avaliacao      setTipo()            Sets the current record's "tipo" value
 * @method tipo_avaliacao      setCriterio()        Sets the current record's "criterio" value
 * @method tipo_avaliacao      setTiposAvaliacao()  Sets the current record's "Tipos_avaliacao" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetipo_avaliacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_avaliacao');
        $this->hasColumn('tipo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('criterio', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('item_cabecalho as Tipos_avaliacao', array(
             'local' => 'id',
             'foreign' => 'tipo_avaliacao_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}