<?php

/**
 * Basesla_evidencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sla_id
 * @property integer $mes_referencia
 * @property string $nao_conformidade
 * @property integer $item_sla_id
 * @property string $unidade_medicao
 * @property integer $quantidade_apurada
 * @property string $observacoes
 * @property string $evidencias
 * @property sla_financeiro $sla_financeiro
 * @property sla_cabecalho $sla_cabecalho
 * @property meses_ano $meses_ano
 * 
 * @method integer        getSlaId()              Returns the current record's "sla_id" value
 * @method integer        getMesReferencia()      Returns the current record's "mes_referencia" value
 * @method string         getNaoConformidade()    Returns the current record's "nao_conformidade" value
 * @method integer        getItemSlaId()          Returns the current record's "item_sla_id" value
 * @method string         getUnidadeMedicao()     Returns the current record's "unidade_medicao" value
 * @method integer        getQuantidadeApurada()  Returns the current record's "quantidade_apurada" value
 * @method string         getObservacoes()        Returns the current record's "observacoes" value
 * @method string         getEvidencias()         Returns the current record's "evidencias" value
 * @method sla_financeiro getSlaFinanceiro()      Returns the current record's "sla_financeiro" value
 * @method sla_cabecalho  getSlaCabecalho()       Returns the current record's "sla_cabecalho" value
 * @method meses_ano      getMesesAno()           Returns the current record's "meses_ano" value
 * @method sla_evidencia  setSlaId()              Sets the current record's "sla_id" value
 * @method sla_evidencia  setMesReferencia()      Sets the current record's "mes_referencia" value
 * @method sla_evidencia  setNaoConformidade()    Sets the current record's "nao_conformidade" value
 * @method sla_evidencia  setItemSlaId()          Sets the current record's "item_sla_id" value
 * @method sla_evidencia  setUnidadeMedicao()     Sets the current record's "unidade_medicao" value
 * @method sla_evidencia  setQuantidadeApurada()  Sets the current record's "quantidade_apurada" value
 * @method sla_evidencia  setObservacoes()        Sets the current record's "observacoes" value
 * @method sla_evidencia  setEvidencias()         Sets the current record's "evidencias" value
 * @method sla_evidencia  setSlaFinanceiro()      Sets the current record's "sla_financeiro" value
 * @method sla_evidencia  setSlaCabecalho()       Sets the current record's "sla_cabecalho" value
 * @method sla_evidencia  setMesesAno()           Sets the current record's "meses_ano" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_evidencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla_evidencia');
        $this->hasColumn('sla_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mes_referencia', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nao_conformidade', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('item_sla_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('unidade_medicao', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('quantidade_apurada', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('observacoes', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('evidencias', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sla_financeiro', array(
             'local' => 'sla_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sla_cabecalho', array(
             'local' => 'item_sla_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('meses_ano', array(
             'local' => 'mes_referencia',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}