<?php

/**
 * BaseLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $chamado_id
 * @property datetime $data_hora
 * @property string $acao
 * @property string $usuario
 * @property string $grupo
 * @property string $justificativa_status
 * @property string $estado
 * @property string $gram
 * @property string $gram_atendimento
 * @property string $contrato
 * @property datetime $data_hora_saida
 * @property string $tipo_de_servico
 * @property string $manutencao
 * @property string $prioridade
 * 
 * @method integer  getChamadoId()            Returns the current record's "chamado_id" value
 * @method datetime getDataHora()             Returns the current record's "data_hora" value
 * @method string   getAcao()                 Returns the current record's "acao" value
 * @method string   getUsuario()              Returns the current record's "usuario" value
 * @method string   getGrupo()                Returns the current record's "grupo" value
 * @method string   getJustificativaStatus()  Returns the current record's "justificativa_status" value
 * @method string   getEstado()               Returns the current record's "estado" value
 * @method string   getGram()                 Returns the current record's "gram" value
 * @method string   getGramAtendimento()      Returns the current record's "gram_atendimento" value
 * @method string   getContrato()             Returns the current record's "contrato" value
 * @method datetime getDataHoraSaida()        Returns the current record's "data_hora_saida" value
 * @method string   getTipoDeServico()        Returns the current record's "tipo_de_servico" value
 * @method string   getManutencao()           Returns the current record's "manutencao" value
 * @method string   getPrioridade()           Returns the current record's "prioridade" value
 * @method Log      setChamadoId()            Sets the current record's "chamado_id" value
 * @method Log      setDataHora()             Sets the current record's "data_hora" value
 * @method Log      setAcao()                 Sets the current record's "acao" value
 * @method Log      setUsuario()              Sets the current record's "usuario" value
 * @method Log      setGrupo()                Sets the current record's "grupo" value
 * @method Log      setJustificativaStatus()  Sets the current record's "justificativa_status" value
 * @method Log      setEstado()               Sets the current record's "estado" value
 * @method Log      setGram()                 Sets the current record's "gram" value
 * @method Log      setGramAtendimento()      Sets the current record's "gram_atendimento" value
 * @method Log      setContrato()             Sets the current record's "contrato" value
 * @method Log      setDataHoraSaida()        Sets the current record's "data_hora_saida" value
 * @method Log      setTipoDeServico()        Sets the current record's "tipo_de_servico" value
 * @method Log      setManutencao()           Sets the current record's "manutencao" value
 * @method Log      setPrioridade()           Sets the current record's "prioridade" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log');
        $this->hasColumn('chamado_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('data_hora', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('acao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('usuario', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('grupo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('justificativa_status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('estado', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('gram', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gram_atendimento', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('contrato', 'string', 255, array(
             'type' => 'string',
             'default' => 'operacional',
             'length' => 255,
             ));
        $this->hasColumn('data_hora_saida', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('tipo_de_servico', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('manutencao', 'string', 255, array(
             'type' => 'string',
             'default' => 'corretiva',
             'length' => 255,
             ));
        $this->hasColumn('prioridade', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}