<?php

/**
 * Basesla_apuracao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sla_id
 * @property integer $item_id
 * @property integer $mes_referencia
 * @property integer $quantidade_nao_conformidade
 * @property decimal $pontuacao_alcancada
 * @property decimal $porcentagem_multa
 * @property sla_financeiro $sla_financeiro
 * @property sla_cabecalho $sla_cabecalho
 * @property meses_ano $meses_ano
 * 
 * @method integer        getSlaId()                       Returns the current record's "sla_id" value
 * @method integer        getItemId()                      Returns the current record's "item_id" value
 * @method integer        getMesReferencia()               Returns the current record's "mes_referencia" value
 * @method integer        getQuantidadeNaoConformidade()   Returns the current record's "quantidade_nao_conformidade" value
 * @method decimal        getPontuacaoAlcancada()          Returns the current record's "pontuacao_alcancada" value
 * @method decimal        getPorcentagemMulta()            Returns the current record's "porcentagem_multa" value
 * @method sla_financeiro getSlaFinanceiro()               Returns the current record's "sla_financeiro" value
 * @method sla_cabecalho  getSlaCabecalho()                Returns the current record's "sla_cabecalho" value
 * @method meses_ano      getMesesAno()                    Returns the current record's "meses_ano" value
 * @method sla_apuracao   setSlaId()                       Sets the current record's "sla_id" value
 * @method sla_apuracao   setItemId()                      Sets the current record's "item_id" value
 * @method sla_apuracao   setMesReferencia()               Sets the current record's "mes_referencia" value
 * @method sla_apuracao   setQuantidadeNaoConformidade()   Sets the current record's "quantidade_nao_conformidade" value
 * @method sla_apuracao   setPontuacaoAlcancada()          Sets the current record's "pontuacao_alcancada" value
 * @method sla_apuracao   setPorcentagemMulta()            Sets the current record's "porcentagem_multa" value
 * @method sla_apuracao   setSlaFinanceiro()               Sets the current record's "sla_financeiro" value
 * @method sla_apuracao   setSlaCabecalho()                Sets the current record's "sla_cabecalho" value
 * @method sla_apuracao   setMesesAno()                    Sets the current record's "meses_ano" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_apuracao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla_apuracao');
        $this->hasColumn('sla_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mes_referencia', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quantidade_nao_conformidade', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pontuacao_alcancada', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('porcentagem_multa', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sla_financeiro', array(
             'local' => 'sla_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sla_cabecalho', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('meses_ano', array(
             'local' => 'mes_referencia',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}