<?php

/**
 * Basenotificacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fop_id
 * @property integer $uf_id
 * @property string $mes
 * @property integer $ano
 * @property string $destinatario
 * @property string $email_destinatario
 * @property string $telefone_destinatario
 * @property string $arquivo_enviado
 * @property boolean $notificacao_foi_enviada
 * @property string $token
 * @property varchar $notificacao_aceita
 * @property string $motivo
 * @property sfGuardUser $sfGuardUser
 * @property sfGuardUf $sfGuardUf
 * 
 * @method integer     getFopId()                   Returns the current record's "fop_id" value
 * @method integer     getUfId()                    Returns the current record's "uf_id" value
 * @method string      getMes()                     Returns the current record's "mes" value
 * @method integer     getAno()                     Returns the current record's "ano" value
 * @method string      getDestinatario()            Returns the current record's "destinatario" value
 * @method string      getEmailDestinatario()       Returns the current record's "email_destinatario" value
 * @method string      getTelefoneDestinatario()    Returns the current record's "telefone_destinatario" value
 * @method string      getArquivoEnviado()          Returns the current record's "arquivo_enviado" value
 * @method boolean     getNotificacaoFoiEnviada()   Returns the current record's "notificacao_foi_enviada" value
 * @method string      getToken()                   Returns the current record's "token" value
 * @method varchar     getNotificacaoAceita()       Returns the current record's "notificacao_aceita" value
 * @method string      getMotivo()                  Returns the current record's "motivo" value
 * @method sfGuardUser getSfGuardUser()             Returns the current record's "sfGuardUser" value
 * @method sfGuardUf   getSfGuardUf()               Returns the current record's "sfGuardUf" value
 * @method notificacao setFopId()                   Sets the current record's "fop_id" value
 * @method notificacao setUfId()                    Sets the current record's "uf_id" value
 * @method notificacao setMes()                     Sets the current record's "mes" value
 * @method notificacao setAno()                     Sets the current record's "ano" value
 * @method notificacao setDestinatario()            Sets the current record's "destinatario" value
 * @method notificacao setEmailDestinatario()       Sets the current record's "email_destinatario" value
 * @method notificacao setTelefoneDestinatario()    Sets the current record's "telefone_destinatario" value
 * @method notificacao setArquivoEnviado()          Sets the current record's "arquivo_enviado" value
 * @method notificacao setNotificacaoFoiEnviada()   Sets the current record's "notificacao_foi_enviada" value
 * @method notificacao setToken()                   Sets the current record's "token" value
 * @method notificacao setNotificacaoAceita()       Sets the current record's "notificacao_aceita" value
 * @method notificacao setMotivo()                  Sets the current record's "motivo" value
 * @method notificacao setSfGuardUser()             Sets the current record's "sfGuardUser" value
 * @method notificacao setSfGuardUf()               Sets the current record's "sfGuardUf" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basenotificacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notificacao');
        $this->hasColumn('fop_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('uf_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mes', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('ano', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('destinatario', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_destinatario', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefone_destinatario', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('arquivo_enviado', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('notificacao_foi_enviada', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('notificacao_aceita', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('motivo', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'fop_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sfGuardUf', array(
             'local' => 'uf_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}