<?php

/**
 * Basefiscalizado_cabecalho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cabecalho_id
 * @property integer $item_fiscalizado_id
 * @property Cabecalho $Cabecalho
 * @property item_fiscalizado $item_fiscalizado
 * 
 * @method integer               getCabecalhoId()         Returns the current record's "cabecalho_id" value
 * @method integer               getItemFiscalizadoId()   Returns the current record's "item_fiscalizado_id" value
 * @method Cabecalho             getCabecalho()           Returns the current record's "Cabecalho" value
 * @method item_fiscalizado      getItemFiscalizado()     Returns the current record's "item_fiscalizado" value
 * @method fiscalizado_cabecalho setCabecalhoId()         Sets the current record's "cabecalho_id" value
 * @method fiscalizado_cabecalho setItemFiscalizadoId()   Sets the current record's "item_fiscalizado_id" value
 * @method fiscalizado_cabecalho setCabecalho()           Sets the current record's "Cabecalho" value
 * @method fiscalizado_cabecalho setItemFiscalizado()     Sets the current record's "item_fiscalizado" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefiscalizado_cabecalho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fiscalizado_cabecalho');
        $this->hasColumn('cabecalho_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_fiscalizado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cabecalho', array(
             'local' => 'cabecalho_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('item_fiscalizado', array(
             'local' => 'item_fiscalizado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}