<?php

/**
 * BasesfGuardUfAfiliado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $afiliado_id
 * @property integer $uf_id
 * @property Afiliado $Afiliado
 * @property sfGuardUf $Uf
 * 
 * @method integer           getAfiliadoId()  Returns the current record's "afiliado_id" value
 * @method integer           getUfId()        Returns the current record's "uf_id" value
 * @method Afiliado          getAfiliado()    Returns the current record's "Afiliado" value
 * @method sfGuardUf         getUf()          Returns the current record's "Uf" value
 * @method sfGuardUfAfiliado setAfiliadoId()  Sets the current record's "afiliado_id" value
 * @method sfGuardUfAfiliado setUfId()        Sets the current record's "uf_id" value
 * @method sfGuardUfAfiliado setAfiliado()    Sets the current record's "Afiliado" value
 * @method sfGuardUfAfiliado setUf()          Sets the current record's "Uf" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUfAfiliado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_uf_afiliado');
        $this->hasColumn('afiliado_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('uf_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Afiliado', array(
             'local' => 'afiliado_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUf as Uf', array(
             'local' => 'uf_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}