<?php

/**
 * Basesla_item_cabecalho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property integer $cabecalho_pai
 * @property sla_cabecalho $sla_cabecalho
 * 
 * @method string             getNome()          Returns the current record's "nome" value
 * @method integer            getCabecalhoPai()  Returns the current record's "cabecalho_pai" value
 * @method sla_cabecalho      getSlaCabecalho()  Returns the current record's "sla_cabecalho" value
 * @method sla_item_cabecalho setNome()          Sets the current record's "nome" value
 * @method sla_item_cabecalho setCabecalhoPai()  Sets the current record's "cabecalho_pai" value
 * @method sla_item_cabecalho setSlaCabecalho()  Sets the current record's "sla_cabecalho" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesla_item_cabecalho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sla_item_cabecalho');
        $this->hasColumn('nome', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3000,
             ));
        $this->hasColumn('cabecalho_pai', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sla_cabecalho', array(
             'local' => 'cabecalho_pai',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}