<?php

/**
 * Basebase_predial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_predio
 * @property string $endereco
 * @property string $estado
 * @property string $cidade
 * @property string $sigla
 * @property string $tipo_imovel
 * @property string $codigo_imovel
 * @property string $categoria
 * @property string $gram
 * @property string $gram_atendimento
 * @property string $regiao
 * @property string $flag
 * @property boolean $ativado
 * @property string $contrato
 * @property string $regional
 * @property Doctrine_Collection $Prediais
 * @property Doctrine_Collection $Localidades
 * 
 * @method integer             getIdPredio()         Returns the current record's "id_predio" value
 * @method string              getEndereco()         Returns the current record's "endereco" value
 * @method string              getEstado()           Returns the current record's "estado" value
 * @method string              getCidade()           Returns the current record's "cidade" value
 * @method string              getSigla()            Returns the current record's "sigla" value
 * @method string              getTipoImovel()       Returns the current record's "tipo_imovel" value
 * @method string              getCodigoImovel()     Returns the current record's "codigo_imovel" value
 * @method string              getCategoria()        Returns the current record's "categoria" value
 * @method string              getGram()             Returns the current record's "gram" value
 * @method string              getGramAtendimento()  Returns the current record's "gram_atendimento" value
 * @method string              getRegiao()           Returns the current record's "regiao" value
 * @method string              getFlag()             Returns the current record's "flag" value
 * @method boolean             getAtivado()          Returns the current record's "ativado" value
 * @method string              getContrato()         Returns the current record's "contrato" value
 * @method string              getRegional()         Returns the current record's "regional" value
 * @method Doctrine_Collection getPrediais()         Returns the current record's "Prediais" collection
 * @method Doctrine_Collection getLocalidades()      Returns the current record's "Localidades" collection
 * @method base_predial        setIdPredio()         Sets the current record's "id_predio" value
 * @method base_predial        setEndereco()         Sets the current record's "endereco" value
 * @method base_predial        setEstado()           Sets the current record's "estado" value
 * @method base_predial        setCidade()           Sets the current record's "cidade" value
 * @method base_predial        setSigla()            Sets the current record's "sigla" value
 * @method base_predial        setTipoImovel()       Sets the current record's "tipo_imovel" value
 * @method base_predial        setCodigoImovel()     Sets the current record's "codigo_imovel" value
 * @method base_predial        setCategoria()        Sets the current record's "categoria" value
 * @method base_predial        setGram()             Sets the current record's "gram" value
 * @method base_predial        setGramAtendimento()  Sets the current record's "gram_atendimento" value
 * @method base_predial        setRegiao()           Sets the current record's "regiao" value
 * @method base_predial        setFlag()             Sets the current record's "flag" value
 * @method base_predial        setAtivado()          Sets the current record's "ativado" value
 * @method base_predial        setContrato()         Sets the current record's "contrato" value
 * @method base_predial        setRegional()         Sets the current record's "regional" value
 * @method base_predial        setPrediais()         Sets the current record's "Prediais" collection
 * @method base_predial        setLocalidades()      Sets the current record's "Localidades" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basebase_predial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('base_predial');
        $this->hasColumn('id_predio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('endereco', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('estado', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('cidade', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sigla', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo_imovel', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('codigo_imovel', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('categoria', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gram', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('gram_atendimento', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('regiao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('flag', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ativado', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('contrato', 'string', 255, array(
             'type' => 'string',
             'default' => 'operacional',
             'length' => 255,
             ));
        $this->hasColumn('regional', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Preventiva as Prediais', array(
             'local' => 'id',
             'foreign' => 'base_predial_id'));

        $this->hasMany('fiscalizacao as Localidades', array(
             'local' => 'id',
             'foreign' => 'base_predial_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}