<?php

/**
 * Baseitem_checklist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $checklist_id
 * @property integer $item_cabecalho_id
 * @property Checklist $Checklist
 * @property item_cabecalho $item_cabecalho
 * 
 * @method integer        getChecklistId()       Returns the current record's "checklist_id" value
 * @method integer        getItemCabecalhoId()   Returns the current record's "item_cabecalho_id" value
 * @method Checklist      getChecklist()         Returns the current record's "Checklist" value
 * @method item_cabecalho getItemCabecalho()     Returns the current record's "item_cabecalho" value
 * @method item_checklist setChecklistId()       Sets the current record's "checklist_id" value
 * @method item_checklist setItemCabecalhoId()   Sets the current record's "item_cabecalho_id" value
 * @method item_checklist setChecklist()         Sets the current record's "Checklist" value
 * @method item_checklist setItemCabecalho()     Sets the current record's "item_cabecalho" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseitem_checklist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_checklist');
        $this->hasColumn('checklist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_cabecalho_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Checklist', array(
             'local' => 'checklist_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('item_cabecalho', array(
             'local' => 'item_cabecalho_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}