<?php

/**
 * Basepesquisa_satisfacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $avaliacao_servico
 * @property Chamado $Satisfacao
 * 
 * @method string              getAvaliacaoServico()  Returns the current record's "avaliacao_servico" value
 * @method Chamado             getSatisfacao()        Returns the current record's "Satisfacao" value
 * @method pesquisa_satisfacao setAvaliacaoServico()  Sets the current record's "avaliacao_servico" value
 * @method pesquisa_satisfacao setSatisfacao()        Sets the current record's "Satisfacao" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepesquisa_satisfacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pesquisa_satisfacao');
        $this->hasColumn('avaliacao_servico', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chamado as Satisfacao', array(
             'local' => 'id',
             'foreign' => 'pesquisa_satisfacao_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}