<?php

/**
 * BaseCiclo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $numero
 * @property Doctrine_Collection $preventiva_ciclos
 * 
 * @method integer             getNumero()            Returns the current record's "numero" value
 * @method Doctrine_Collection getPreventivaCiclos()  Returns the current record's "preventiva_ciclos" collection
 * @method Ciclo               setNumero()            Sets the current record's "numero" value
 * @method Ciclo               setPreventivaCiclos()  Sets the current record's "preventiva_ciclos" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCiclo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ciclo');
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Preventiva as preventiva_ciclos', array(
             'local' => 'id',
             'foreign' => 'ciclo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}