<?php

/**
 * Basefiscalizacao_item_cabecalho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $fiscalizacao_cabecalho_id
 * @property string $nome
 * @property integer $tipo_avaliacao_id
 * @property fiscalizacao_cabecalho $fiscalizacao_cabecalho
 * @property tipo_avaliacao $tipo_avaliacao
 * @property Doctrine_Collection $Itens_cabecalho
 * 
 * @method integer                     getFiscalizacaoCabecalhoId()   Returns the current record's "fiscalizacao_cabecalho_id" value
 * @method string                      getNome()                      Returns the current record's "nome" value
 * @method integer                     getTipoAvaliacaoId()           Returns the current record's "tipo_avaliacao_id" value
 * @method fiscalizacao_cabecalho      getFiscalizacaoCabecalho()     Returns the current record's "fiscalizacao_cabecalho" value
 * @method tipo_avaliacao              getTipoAvaliacao()             Returns the current record's "tipo_avaliacao" value
 * @method Doctrine_Collection         getItensCabecalho()            Returns the current record's "Itens_cabecalho" collection
 * @method fiscalizacao_item_cabecalho setFiscalizacaoCabecalhoId()   Sets the current record's "fiscalizacao_cabecalho_id" value
 * @method fiscalizacao_item_cabecalho setNome()                      Sets the current record's "nome" value
 * @method fiscalizacao_item_cabecalho setTipoAvaliacaoId()           Sets the current record's "tipo_avaliacao_id" value
 * @method fiscalizacao_item_cabecalho setFiscalizacaoCabecalho()     Sets the current record's "fiscalizacao_cabecalho" value
 * @method fiscalizacao_item_cabecalho setTipoAvaliacao()             Sets the current record's "tipo_avaliacao" value
 * @method fiscalizacao_item_cabecalho setItensCabecalho()            Sets the current record's "Itens_cabecalho" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefiscalizacao_item_cabecalho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fiscalizacao_item_cabecalho');
        $this->hasColumn('fiscalizacao_cabecalho_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo_avaliacao_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('fiscalizacao_cabecalho', array(
             'local' => 'fiscalizacao_cabecalho_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('tipo_avaliacao', array(
             'local' => 'tipo_avaliacao_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('fiscalizacao_item_checklist as Itens_cabecalho', array(
             'local' => 'id',
             'foreign' => 'fiscalizacao_item_cabecalho_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}