<?php

/**
 * Basefiscalizacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $base_predial_id
 * @property integer $contract_id
 * @property integer $user_id
 * @property string $relatorio_fotografico
 * @property string $observacao
 * @property datetime $data_de_execucao
 * @property integer $num_nao_conformidade
 * @property decimal $nota_estacao
 * @property base_predial $base_predial
 * @property sfGuardUser $sfGuardUser
 * @property sfGuardContract $sfGuardContract
 * 
 * @method integer         getBasePredialId()         Returns the current record's "base_predial_id" value
 * @method integer         getContractId()            Returns the current record's "contract_id" value
 * @method integer         getUserId()                Returns the current record's "user_id" value
 * @method string          getRelatorioFotografico()  Returns the current record's "relatorio_fotografico" value
 * @method string          getObservacao()            Returns the current record's "observacao" value
 * @method datetime        getDataDeExecucao()        Returns the current record's "data_de_execucao" value
 * @method integer         getNumNaoConformidade()    Returns the current record's "num_nao_conformidade" value
 * @method decimal         getNotaEstacao()           Returns the current record's "nota_estacao" value
 * @method base_predial    getBasePredial()           Returns the current record's "base_predial" value
 * @method sfGuardUser     getSfGuardUser()           Returns the current record's "sfGuardUser" value
 * @method sfGuardContract getSfGuardContract()       Returns the current record's "sfGuardContract" value
 * @method fiscalizacao    setBasePredialId()         Sets the current record's "base_predial_id" value
 * @method fiscalizacao    setContractId()            Sets the current record's "contract_id" value
 * @method fiscalizacao    setUserId()                Sets the current record's "user_id" value
 * @method fiscalizacao    setRelatorioFotografico()  Sets the current record's "relatorio_fotografico" value
 * @method fiscalizacao    setObservacao()            Sets the current record's "observacao" value
 * @method fiscalizacao    setDataDeExecucao()        Sets the current record's "data_de_execucao" value
 * @method fiscalizacao    setNumNaoConformidade()    Sets the current record's "num_nao_conformidade" value
 * @method fiscalizacao    setNotaEstacao()           Sets the current record's "nota_estacao" value
 * @method fiscalizacao    setBasePredial()           Sets the current record's "base_predial" value
 * @method fiscalizacao    setSfGuardUser()           Sets the current record's "sfGuardUser" value
 * @method fiscalizacao    setSfGuardContract()       Sets the current record's "sfGuardContract" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefiscalizacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fiscalizacao');
        $this->hasColumn('base_predial_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contract_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('relatorio_fotografico', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('observacao', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('data_de_execucao', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('num_nao_conformidade', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nota_estacao', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('base_predial', array(
             'local' => 'base_predial_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('sfGuardContract', array(
             'local' => 'contract_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}