<?php

/**
 * Basepreventiva_tipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $descricao
 * @property Doctrine_Collection $Cabecalho
 * @property Doctrine_Collection $sfGuardUf
 * @property Doctrine_Collection $Preventiva_tipos
 * @property Doctrine_Collection $preventiva_tipo_cabecalho
 * @property Doctrine_Collection $preventiva_tipo_uf
 * @property Doctrine_Collection $preventiva_tipos
 * @property Doctrine_Collection $Tipos
 * @property Doctrine_Collection $contratoManutencao
 * @property Doctrine_Collection $valores_manutencao_tipo
 * 
 * @method string              getNome()                      Returns the current record's "nome" value
 * @method string              getDescricao()                 Returns the current record's "descricao" value
 * @method Doctrine_Collection getCabecalho()                 Returns the current record's "Cabecalho" collection
 * @method Doctrine_Collection getSfGuardUf()                 Returns the current record's "sfGuardUf" collection
 * @method Doctrine_Collection getPreventivaTipos()           Returns the current record's "Preventiva_tipos" collection
 * @method Doctrine_Collection getPreventivaTipoCabecalho()   Returns the current record's "preventiva_tipo_cabecalho" collection
 * @method Doctrine_Collection getPreventivaTipoUf()          Returns the current record's "preventiva_tipo_uf" collection
 * @method Doctrine_Collection getPreventivaTipos()           Returns the current record's "preventiva_tipos" collection
 * @method Doctrine_Collection getTipos()                     Returns the current record's "Tipos" collection
 * @method Doctrine_Collection getContratoManutencao()        Returns the current record's "contratoManutencao" collection
 * @method Doctrine_Collection getValoresManutencaoTipo()     Returns the current record's "valores_manutencao_tipo" collection
 * @method preventiva_tipo     setNome()                      Sets the current record's "nome" value
 * @method preventiva_tipo     setDescricao()                 Sets the current record's "descricao" value
 * @method preventiva_tipo     setCabecalho()                 Sets the current record's "Cabecalho" collection
 * @method preventiva_tipo     setSfGuardUf()                 Sets the current record's "sfGuardUf" collection
 * @method preventiva_tipo     setPreventivaTipos()           Sets the current record's "Preventiva_tipos" collection
 * @method preventiva_tipo     setPreventivaTipoCabecalho()   Sets the current record's "preventiva_tipo_cabecalho" collection
 * @method preventiva_tipo     setPreventivaTipoUf()          Sets the current record's "preventiva_tipo_uf" collection
 * @method preventiva_tipo     setPreventivaTipos()           Sets the current record's "preventiva_tipos" collection
 * @method preventiva_tipo     setTipos()                     Sets the current record's "Tipos" collection
 * @method preventiva_tipo     setContratoManutencao()        Sets the current record's "contratoManutencao" collection
 * @method preventiva_tipo     setValoresManutencaoTipo()     Sets the current record's "valores_manutencao_tipo" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepreventiva_tipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preventiva_tipo');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cabecalho', array(
             'refClass' => 'preventiva_tipo_cabecalho',
             'local' => 'preventiva_tipo_id',
             'foreign' => 'cabecalho_id'));

        $this->hasMany('sfGuardUf', array(
             'refClass' => 'preventiva_tipo_uf',
             'local' => 'preventiva_tipo_id',
             'foreign' => 'uf_id'));

        $this->hasMany('servico_uf as Preventiva_tipos', array(
             'local' => 'id',
             'foreign' => 'preventiva_tipo_id'));

        $this->hasMany('preventiva_tipo_cabecalho', array(
             'local' => 'id',
             'foreign' => 'preventiva_tipo_id'));

        $this->hasMany('preventiva_tipo_uf', array(
             'local' => 'id',
             'foreign' => 'preventiva_tipo_id'));

        $this->hasMany('Preventiva as preventiva_tipos', array(
             'local' => 'id',
             'foreign' => 'preventiva_tipo_id'));

        $this->hasMany('sla_cabecalho as Tipos', array(
             'local' => 'id',
             'foreign' => 'tipo_manutencao_id'));

        $this->hasMany('contrato_fornecedor as contratoManutencao', array(
             'local' => 'id',
             'foreign' => 'tipo_manutencao_id'));

        $this->hasMany('sla_valores_totais as valores_manutencao_tipo', array(
             'local' => 'id',
             'foreign' => 'tipo_manutencao_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}