<?php

/**
 * Afiliado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Afiliado extends BaseAfiliado
{

 /*
  * Retornar a lista de chamados de uma determinada regional
  */
  public function getChamados()
  {
    $q = Doctrine_Query::create()
      ->select('j.*')
      ->from('Controle j');

    $q = Doctrine_Core::getTable('Controle')->addControleWebServiceQuery($q, $this->getUf(), $this->getGram(), $this->getContract());
 
    return $q->execute();
  }

 /*
  * Retornar a lista de chamados de uma determinada regional
  */
  public function getChamadosPorStatus($status)
  {
    $q = Doctrine_Query::create()
      ->select('j.*')
      ->from('Controle j');
      
    $q = Doctrine_Core::getTable('Controle')->addControleStatusWebServiceQuery($q, $status, $this->getUf(), $this->getGram(), $this->getContract());
 
    return $q->execute();
  } 

/*
 * Gerar token ao salvar formulario
 */
  public function save(Doctrine_Connection $conn = null)
  {
    if (!$this->getToken())
    {
      $this->setToken(sha1($this->getEmail().rand(11111, 99999)));
    }
 
    return parent::save($conn);
  }

 /*
  * Ativar afiliado
  */
  public function activate()
  {
    $this->setAtivado(true); 
    return $this->save();
  }
 
 /*
  * Desativar afiliado
  */
  public function deactivate()
  {
    $this->setAtivado(false); 
    return $this->save();
  }

}