<?php

/**
 * AfiliadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AfiliadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AfiliadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Afiliado');
    }
	

	static public $empresas = array(
		'araujoabreu.com.br' => 'Araújo Abreu',
		'elfe.com.br' => 'Elfe',
		'eqsengenharia.com.br' => 'EQS',
		'oi.net.br' => 'Oi',
	);

	public function getEmpresas(){
		return	self::$empresas;
	}		
	

	
}