<?php

/**
 * Base_predial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class base_predial extends BaseBase_predial
{

  /*
   *
   */
  public function asArray($host)
   {
     return array(
       'id'           => $this->getId(),
       'id_predio'    => $this->getIdPredio(),
       'endereco'     => $this->getEndereco(),
       'estado'       => $this->getEstado(),
       'cidade'       => $this->getCidade(),
       'sigla'        => $this->getSigla(),
       'tipo_imovel'  => $this->getTipoImovel(),
       'categoria'    => $this->getCategoria(),
       'gram'         => $this->getGram(),
       'gram_atendimento' => $this->getGramAtendimento(),
       'regiao'       => $this->getRegiao(),
       'flag'         => $this->getFlag(),
       'contrato'     => $this->getContrato(),
       'regional'     => $this->getRegional()
    );
  }

   public function updateLuceneIndex()
  {
       $index = Base_predialTable::getLuceneIndex();

    // remover entradas existentes
       foreach ($index->find('pk:'.$this->getId()) as $hit)
       {
         $index->delete($hit->id);
       }

       $doc = new Zend_Search_Lucene_Document();

    // armazene a chave primária local para identificá-la nos resultados da pesquisa
       $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));

    // indexar campos locais
       $doc->addField(Zend_Search_Lucene_Field::UnStored('id_predio', $this->getIdPredio(), 'utf-8'));
       $doc->addField(Zend_Search_Lucene_Field::UnStored('endereco', $this->getEndereco(), 'utf-8'));
       $doc->addField(Zend_Search_Lucene_Field::UnStored('estado', $this->getEstado(), 'utf-8'));
       $doc->addField(Zend_Search_Lucene_Field::UnStored('cidade', $this->getCidade(), 'utf-8'));
       $doc->addField(Zend_Search_Lucene_Field::UnStored('sigla', $this->getSigla(), 'utf-8'));
       $doc->addField(Zend_Search_Lucene_Field::UnStored('gram', $this->getGram(), 'utf-8'));

    // adicionar local ao índice
       $index->addDocument($doc);
       $index->commit();
 }
}
