<?php

/**
 * cabecalho_ufTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class cabecalho_ufTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object cabecalho_ufTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cabecalho_uf');
    }
}