<?php

/**
 * Chamado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chamado extends BaseChamado
{
   public function _toString()
   {
     return sprintf('%s %s %s %s %s %s %s %s %s %s %s %s', $this->getNome(), $this->getEmail(), $this->getCelular(), $this->getEstado(), $this->getSiglaDaEstacao(), $this->getCidade(), $this->getEndereco(), $this->getComplemento(), $this->getTipoDeServico(), $this->getRecursoServicoRequerido(), $this->getJustificativa(), $this->getAnexos());  
   }

 /*
  * Publicar chamado
  */
  public function publish($flag)
  {
    if($flag == "Preventiva") $this->setStatus("Em análise pelo fornecedor");
    else $this->setStatus("Em análise pela Oi");

    if($this->getPrioridade() == "Preventiva"){
      $this->setJustificativaStatus("Usuário está de acordo que solicitação seja realizada na preventiva");
    }
    elseif($this->getPrioridade() == "Emergencial") {
      $this->setJustificativaStatus("Usuário informou em sua solicitação que o serviço demandado coloca em risco pessoas ou equipamentos e que por isso precisa ser resolvido entre hoje e amanhã");
    }
    elseif($flag == "Sob Demanda"){
      $this->setJustificativaStatus("Chamado em análise pela Oi, por ser uma localidade atendida Sob Demanda");
    }
    else{
      $this->setJustificativaStatus("Chamado aguardando análise do fornecedor");
    }

    $this->save();
  }

 /*
  *
  */
  public function reabrir($justificativa_status)
  {
    $this->setStatus("Em análise pelo fornecedor");
    $this->setJustificativaStatus($justificativa_status);

    $this->setAnexos(null);
    $this->setPesquisaSatisfacaoId(null);
    $this->setDataDeExecucao(null);
    $this->setDataProgramada(null);
    $this->setRelatorioFotografico(null);
    $this->setOrcamentoId(null);
    $this->setJustificativa("Solicitação anterior: ".$this->getJustificativa()." / Motivo da reabertura: ".$justificativa_status);
    $this->save();
  }


  /*
  * Publicar pesquisa
  */
  public function publicarPesquisa($pesquisa)
  {
    $this->setPesquisaSatisfacao($pesquisa);
    $this->setPesquisaSatisfacaoId($pesquisa);
    $this->save();
  }

}
