<?php

/**
 * ChecklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChecklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChecklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Checklist');
    }
}