<?php

/**
 * contrato_fornecedorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class contrato_fornecedorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object contrato_fornecedorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('contrato_fornecedor');
    }
	
	public function getFornecedoresPorUF($filial){
       return $this->hasFornecedoresPorUF($filial)->execute();
    }
   
	public function hasFornecedoresPorUF($filial){
	   $q = Doctrine_Query::create()
		 // ->select('id')
		  ->from('contrato_fornecedor a')
		  ->innerJoin('fornecedor b')
		  ->where('a.filial_id = ?', $filial);
      return $q; 
	}
	
	
	public function getValorContratoPorTipo($filial, $fornecedor, $tipo_manutencao_id){
       return $this->hasvalor($filial, $fornecedor, $tipo_manutencao_id)->execute();
    }
   
	public function hasvalor($filial, $fornecedor, $tipo_manutencao_id){
	   $q = Doctrine_Query::create()
		  ->select('fornecedor_id, valor_mensal, tipo_manutencao_id')
		  ->from('contrato_fornecedor')
		  ->where('filial_id = ?', $filial)
		  ->andWhere('fornecedor_id = ?', $fornecedor)
		  ->andWhere('tipo_manutencao_id = ?', $tipo_manutencao_id)
		  ->orderBy('tipo_manutencao_id ASC');
      return $q; 
	}
	

	public function getNumeroContrato($fornecedor, $filialId, $tipo_manutencao_id){
       return $this->hasNumero($fornecedor, $filialId, $tipo_manutencao_id)->execute();
    }
   
	public function hasNumero($fornecedor, $filialId, $tipo_manutencao_id){
	   $q = Doctrine_Query::create()
		  ->select('*')
		  ->from('contrato_fornecedor')
		  ->where('filial_id = ?', $filialId)
		  ->andWhere('fornecedor_id = ?', $fornecedor)
		  ->andWhere('tipo_manutencao_id = ?', $tipo_manutencao_id);
      return $q; 
	}
	
}