<?php

/**
 * Diverso_itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Diverso_itemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Diverso_itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Diverso_item');
    }

     /*
    * Retonar orcamento
    */
   public function getDiversos(Doctrine_Query $q = null, $id)
   {
    return $this->addDiversosQuery($q, $id)->execute();
   }


   /*
    * Query para recuperar orcamento
    */
   public function addDiversosQuery(Doctrine_Query $q = null, $id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Diverso_item j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.orcamento_id = ?', $id);

      return $q;
   }

   /*
    * Deletar todos os itens do orcamento na tabela correspondente
    */
    public function deleteItensOrcamento(Doctrine_Query $q = null) {
        $this->addItemDiversoQuery($q)->execute();
    }

    public function getTodosItensOrcamento(Doctrine_Query $q = null) {
        return $this->addItemDiversoQuery($q)->execute();
    }

   /*
    * Buscar item diverso
    */
    protected function addItemDiversoQuery (Doctrine_Query $q = null){

      if (is_null($q)) {
        $q = Doctrine_Query::create()
          ->from('Diverso_item j');
      }

      $alias = $q->getRootAlias();

      return $q;
    }

}
