<?php

/**
 * extintor_tipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class extintor_tipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object extintor_tipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('extintor_tipo');
    }
}