<?php

/**
 * ExtintorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtintorTable extends item_checklistTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtintorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Extintor');
    }


    /*
   * Retonar extintor de um determinado checklist
   */
   public function getExtintorChecklist($checklist_id)
   {
    return $this->addExtintorChecklistQuery(null, $checklist_id)->execute();
   }


   /*
    * Query para selecionar os extintores de um determinado checklist
    */
   public function addExtintorChecklistQuery(Doctrine_Query $q = null, $checklist_id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Extintor j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.checklist_id = ?', $checklist_id);

     return $q;
   } 

   /*
    * Deletar todos os itens do checklist na tabela correspondente
    */
    public function deleteItens(Doctrine_Query $q = null, $checklist_id) {
        $this->addExtintorChecklistQuery($q, $checklist_id)->execute();
    }

}