<?php

/**
 * fiscalizacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiscalizacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiscalizacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiscalizacao');
    }

    /*
    * Query para recuperar chamados
    */
   public function addFiscalizacaoQuery(Doctrine_Query $q = null, $uf, $gram, $contrato)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Fiscalizacao j');
     }

	 $alias = $q->getRootAlias();
	 $q->leftJoin($alias.'.base_predial a');	    

	 //uf
	   if(count($uf)>0){
	     $aux = 'a.estado = "'.$uf[0]->getName().'"';

	     for($x = 1; $x < count($uf); $x++){
	       $aux = $aux.' OR a.estado = "'.$uf[$x]->getName().'"';
	     }

	     $q->andWhere($aux);
	    }

     //gram
       if(count($gram)>0){
           $aux1 = 'a.gram = "'.$gram[0]->getName().'"';
        
           for($x = 1; $x < count($gram); $x++){
             $aux1 = $aux1.' OR a.gram = "'.$gram[$x]->getName().'"';
           }
       
         $q->andWhere($aux1);
        }

     //contrato
       if(count($contrato)>0){
         $aux2 = 'a.contrato = "'.$contrato[0]->getName().'"';

         for($x = 0; $x < count($contrato); $x++){
            $aux2 = $aux2.' OR a.contrato = "'.$contrato[$x]->getName().'"';
         }

         $q->andWhere($aux2);
        }

        $q->addOrderBy($alias.'.created_at ASC LIMIT 1000');

        return $q;
    }
}