<?php

/**
 * fiscalizacao_item_cabecalhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiscalizacao_item_cabecalhoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiscalizacao_item_cabecalhoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiscalizacao_item_cabecalho');
    }
	

	/**
     * Retorna itens de cabecalhos de um determinado cabecalho
     *
     * @return array item_cabecalho
     */
    public function getItensCabecalho(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
		  ->select(j.id, j.fiscalizacao_cabecalho_id, j.nome, j.tipo_avaliacao_id, a.tipo) 		
	      ->from('fiscalizacao_item_cabecalho j')
		  ->leftJoin('tipo_avaliacao a');
	  }
 
	  return $q->execute();
	}

}