<?php

/**
 * fiscalizacao_cabecalhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiscalizacao_cabecalhoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiscalizacao_cabecalhoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiscalizacao_cabecalho');
    }
	
}