<?php

/**
 * fiscalizacao_item_checklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiscalizacao_item_checklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiscalizacao_item_checklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiscalizacao_item_checklist');
    }
}