<?php

/**
 * fiscalizacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class fiscalizacao extends Basefiscalizacao
{

	/**
     * Retorna os sla de um determinada fiscalizacao
     *
     * @return array sla
     */
	public function getSLA()
	{
	  $q = Doctrine_Query::create()
	    ->from('sla s')
	    ->where('s.fiscalizacao_id = ?', $this->getId());
	 
	  return Doctrine_Core::getTable('sla')->getSLA($q);
	}

}