<?php

/**
 * fiscalizacao_extintorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiscalizacao_extintorTable extends fiscalizacao_item_checklistTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiscalizacao_extintorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiscalizacao_extintor');
    }

     /*
   * Retonar extintor de um determinado fiscalizacao
   */
   public function getExtintorFiscalizacao($fiscalizacao_id)
   {
    return $this->addExtintorFiscalizacaoQuery(null, $fiscalizacao_id)->execute();
   }


   /*
    * Query para selecionar os extintores de um determinado fiscalizacao
    */
   public function addExtintorFiscalizacaoQuery(Doctrine_Query $q = null, $fiscalizacao_id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('fiscalizacao_extintor f');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.fiscalizacao_id = ?', $fiscalizacao_id);

     return $q;
   } 
}