<?php

/**
 * fiscalizacao_itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiscalizacao_itemTable extends fiscalizacao_item_checklistTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiscalizacao_itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiscalizacao_item');
    }

    /*
   * Retonar itens de um determinado fiscalizacao
   */
   public function getItensFiscalizacao($fiscalizacao_id)
   {
    return $this->addItensFiscalizacaoQuery(null, $fiscalizacao_id)->execute();
   }


   /*
    * Query para selecionar os itens de um determinado fiscalizacao
    */
   public function addItensFiscalizacaoQuery(Doctrine_Query $q = null, $fiscalizacao_id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('fiscalizacao_item f');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.fiscalizacao_id = ?', $fiscalizacao_id);

     return $q;
   }
}