<?php

/**
 * fornecedorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fornecedorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fornecedorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fornecedor');
    }
	
	
	/*
   * Retonar a data de realizacao da ultima preventiva
   */
  public function getFornecedorPorUF($uf){
    return $this->addFornecedorQuery($uf)->execute();
  }


  /*
   * Query para retornar a data de realizacao da ultima preventiva
   */
  public function addFornecedorQuery($uf){

    $q = Doctrine_Query::create()
    ->from('Fornecedor j');
     

     $alias = $q->getRootAlias();

     $q->innerJoin($alias.'.contrato_fornecedor a');

     $q->where('a.fornecedor_id = ?', $uf);
     //$q->orderBy($alias.'.updated_at DESC');
     return $q;
  }  
  
  
/*  
  
   public function getFornecedoresPorUF($filial){
       return $this->hasFornecedoresPorUF($filial)->execute();
    }
   
	public function hasFornecedoresPorUF($filial){
	   $q = Doctrine_Query::create()
		  ->select('b.valor_mensal, a.id, a.nome')
		  ->from('contrato_fornecedor b')
		  ->leftJoin('b.fornecedor a')
		 // ->innerJoin('contrato_fornecedor b')
		  ->where('b.filial_id = 60');
		  //->groupBy('f.nome');
      return $q; 
	}
  
*/	
	

   public function getNomeFornecedor( $filial)
   {
        return $this->addNomeFornecedorQuery( $filial)->execute();
   }
	
	
	
	  public function addNomeFornecedorQuery( $filial)
   {
      $q = Doctrine_Query::create()
      ->select(' j.id, j.nome')
      ->from('fornecedor j');
     
      $alias = $q->getRootAlias();
      $q->innerJoin($alias.'.contrato_fornecedor a');
      $q->andWhere('a.filial_id = ?', $filial);

    
     return $q;
   }
  
}