<?php

/**
 * item_checklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class item_checklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object item_checklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('item_checklist');
    }

 
}