<?php

/**
 * Log
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Log extends BaseLog
{
   /*
  * Atualizar Log anterior
  */
  public function atualizar()
  {
    $this->setDataHoraSaida(date('Y-m-d H:i:s'));
    $this->save();
  }


  /*
   * Busca nome e sobrenome baseado do usuário 
   */
   public function buscaNomeUsuario($user)
   {
	 
      $q = Doctrine_Query::create()
         ->select('first_name, last_name')
         ->from('sfGuardUser')
		 ->where('username = ?', $user);
	 
		 return $q->fetchOne();
   }
}
