<?php

/**
 * lpu_servicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class lpu_servicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object lpu_servicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('lpu_servico');
    }

   /*
    * Query Servico com base no codigo
    */
   public function addServicoQuery(Doctrine_Query $q = null, $codigo, $uf)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('lpu_servico j');
     }

     $alias = $q->getRootAlias();

     $q->andWhere($alias.'.codigo = ?', $codigo);
     $q->andWhere($alias.'.estado = ?', $uf);

     return $q;
   }

   /*
    * Retonar servico da LPU
    */
   public function getServico(Doctrine_Query $q = null, $codigo, $uf)
   {
        return $this->addServicoQuery($q, $codigo, $uf)->execute();
   }

}
