<?php

/**
 * lpu_materialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class lpu_materialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object lpu_materialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('lpu_material');
    }

   /*
    * Query material com base no codigo
    */
   public function addMaterialQuery(Doctrine_Query $q = null, $codigo, $uf)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('lpu_material j');
     }

     $alias = $q->getRootAlias();

     $q->andWhere($alias.'.codigo = ?', $codigo);
     $q->andWhere($alias.'.estado = ?', $uf);

     return $q;
   }


   /*
    * Retonar Material
    */
   public function getMaterial(Doctrine_Query $q = null, $codigo, $uf)
   {
        return $this->addMaterialQuery($q, $codigo, $uf)->execute();
   }

}
