<?php

/**
 * ManutencaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManutencaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManutencaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manutencao');
    }
}