<?php

/**
 * Material_itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Material_itemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Material_itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Material_item');
    }


   /*
    * Retonar orcamento
    */
   public function getMateriais(Doctrine_Query $q = null, $id)
   {
    return $this->addMateriaisQuery($q, $id)->execute();
   }



   /*
    * Query para recuperar orcamento
    */
   public function addMateriaisQuery(Doctrine_Query $q = null, $id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Material_item j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.orcamento_id = ?', $id);

      return $q;
   }

   /*
    * Deletar todos os itens do orcamento na tabela correspondente
    */
    public function deleteItensOrcamento(Doctrine_Query $q = null) {
        $this->addItemLPUQuery($q)->execute();
    }

    public function getTodosItensOrcamento(Doctrine_Query $q = null) {
        return $this->addItemLPUQuery($q)->execute();
    }     

   /*
    * Buscar item diverso
    */
    protected function addItemLPUQuery  (Doctrine_Query $q = null){

      if (is_null($q)) {
        $q = Doctrine_Query::create()
          ->from('Material_item j');
      }

      $alias = $q->getRootAlias();

      return $q;
    }

}
