<?php

/**
 * meses_anoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class meses_anoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object meses_anoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('meses_ano');
    }


   /*
    * Buscar mes escrito por extenso
    */
    public function getMes($mesPorExtenso)
   {
		return $this->addMesQuery($mesPorExtenso)->execute();
   }
	

    public function addMesQuery($mesPorExtenso)
   {
      $q = Doctrine_Query::create()
	  ->select('id')
      ->from('meses_ano');
     
      $q->where('name = ?', $mesPorExtenso);
      return $q;
   }

}