<?php

/**
 * notificacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class notificacaoTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object notificacaoTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('notificacao');
  }
	
   
   /*
    * Retonar as notificacoes de um determinado estado
    */
   public function getNotificacoes(Doctrine_Query $q = null, $uf)
   {
    return $this->addNotificacoesQuery($q, $uf)->execute();
   }
   
   
   /*
    * Query para recuperar as notificacoes de um determinado estado
    */  
   public function addNotificacoesQuery(Doctrine_Query $q = null, $uf)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->select('n.id, n.mes, n.ano, n.notificacao_foi_enviada, s.name')  
         ->from('notificacao n');
     }

     $alias = $q->getRootAlias();
     
     //uf
     if(count($uf)>0){
       $aux = $alias.'.uf_id = "'.$uf[0]->getId().'"';

       for($x = 1; $x < count($uf); $x++){
         $aux = $aux.' OR '.$alias.'.uf_id = "'.$uf[$x]->getId().'"';
       }

       $q->andWhere($aux);
     }

      $q->orderBy($alias.'.created_at DESC LIMIT 1000');
      
      return $q;

   }    
   
    /*
    * Retonar se token existe
    */
   public function  getExistToken($token, $id)
   {
    return $this->addTokenQuery($token, $id)->count();
   }
   
   /*
    * Query para retornar se token existe
    */
   public function addTokenQuery($token, $id)
   {
    	$q = Doctrine_Query::create()
		  ->select('n.id')	
  		->from('notificacao n')
		  ->where('n.id = ?', $id)
		  ->andWhere('n.token = ?', $token);
     
	     return $q;
   }    
	
}