<?php

/**
 * notificacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class notificacao extends Basenotificacao
{

  /*
   * Atualizar notificacao
   */
  public function atualizar($avaliacao, $motivo)
  {
	$this->setToken(sha1(rand(1111,9999)));  
    $this->setNotificacaoAceita($avaliacao);
    $this->setMotivo($motivo);
    $this->save();
  }  

}