<?php

/**
 * pesquisa_satisfacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pesquisa_satisfacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pesquisa_satisfacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pesquisa_satisfacao');
    }
}