<?php

/**
 * Pini_itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Pini_itemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Pini_itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pini_item');
    }

   /*
    * Retonar orcamento
    */
   public function getPini(Doctrine_Query $q = null, $id)
   {
    return $this->addPiniQuery($q, $id)->execute();
   }

   /*
    * Query para recuperar orcamento
    */
   public function addPiniQuery(Doctrine_Query $q = null, $id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Pini_item j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.orcamento_id = ?', $id);

      return $q;
   }

   /*
    * Deletar todos os itens do orcamento na tabela correspondente
    */
    public function deleteItensOrcamento(Doctrine_Query $q = null) {
        $this->addItemPiniQuery($q)->execute();
    }

    public function getTodosItensOrcamento(Doctrine_Query $q = null) {
        return $this->addItemPiniQuery($q)->execute();
    } 

   /*
    * Buscar item diverso
    */
    protected function addItemPiniQuery (Doctrine_Query $q = null){

      if (is_null($q)) {
        $q = Doctrine_Query::create()
          ->from('Pini_item j');
      }

      $alias = $q->getRootAlias();

      return $q;
    }
}