<?php

/**
 * precoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class precoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object precoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('preco');
    }

     /*
    * Query Preco com base no codigo
    */
   public function addPrecoQuery(Doctrine_Query $q = null, $codigo, $uf)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Preco j');
     }

     $alias = $q->getRootAlias();

     $q->innerJoin($alias.'.Pini a');
     $q->andWhere('a.cod_pini = ?', $codigo);

     $q->andWhere($alias.'.uf_id = ?', $uf);
    
     return $q;
   }

   /*
    * Retonar preco do servico da PINI
    */
   public function getPreco(Doctrine_Query $q = null, $codigo, $uf)
   {
        return $this->addPrecoQuery($q, $codigo, $uf)->execute(array(), Doctrine::HYDRATE_SCALAR);
   }
}