<?php

/**
 * preventiva_tipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class preventiva_tipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object preventiva_tipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('preventiva_tipo');
    }
}