<?php

/**
 * preventiva_tipo_cabecalhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class preventiva_tipo_cabecalhoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object preventiva_tipo_cabecalhoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('preventiva_tipo_cabecalho');
    }
}