<?php

/**
 * preventiva_tipo_ufTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class preventiva_tipo_ufTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object preventiva_tipo_ufTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('preventiva_tipo_uf');
    }
}