<?php

/**
 * ServicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servico');
    }

   /*
    * Query siglas
    */
   public function addServicosQuery(Doctrine_Query $q = null, $groups)
   {
      $q = Doctrine_Query::create()
         ->from('Servico j')
         ->leftJoin('j.servico_grupo a')
         ->where('a.group_id = "'.$groups[0]->getId().'"')
         ->groupBy('j.servico_id')          
         ->addOrderBy('tipo_de_servico');

      return $q;
   }

   /*
    * Retonar Siglas
    */
   public function getServicos(Doctrine_Query $q = null, $groups)
   {
        return $this->addServicosQuery($q, $groups)->execute();
   }

  /*
   * Query recursos com base no id do servico
   */
   public function addRecursosQuery(Doctrine_Query $q = null, $servico_id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Servico j');
     }

     $alias = $q->getRootAlias();

     $q->andWhere($alias.'.servico_id = ?', $servico_id);
     $q->addOrderBy('recurso_servico_requerido');

      return $q;
   }


   /*
    * Retonar Siglas
    */
   public function getRecursos(Doctrine_Query $q = null, $servico_id)
   {
        return $this->addRecursosQuery($q, $servico_id)->execute();
   }


   
	public function getTodosServicos(){
		return $this->addServicos()->execute();
	}
	
	public function addServicos(){
		$q = Doctrine_Query::create()
         ->from('Servico j')
		 ->orderBy('tipo_de_servico asc')
		 ->groupBy('tipo_de_servico');
      
      return $q;
	}
	
	
	

}
