<?php

/**
 * Servico_itemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Servico_itemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Servico_itemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servico_item');
    }

    /*
    * Retonar orcamento
    */
   public function getServicos(Doctrine_Query $q = null, $id)
   {
    return $this->addServicosQuery($q, $id)->execute();
   }


   /*
    * Query para recuperar orcamento
    */
   public function addServicosQuery(Doctrine_Query $q = null, $id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('Servico_item j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.orcamento_id = ?', $id);

      return $q;
   }

   /*
    * Deletar todos os itens do orcamento na tabela correspondente
    */
    public function deleteItensOrcamento(Doctrine_Query $q = null) {
        $this->addItemServicoQuery($q)->execute();
    }

    public function getTodosItensOrcamento(Doctrine_Query $q = null) {
        return $this->addItemServicoQuery($q)->execute();
    } 

   /*
    * Buscar item servico
    */
    protected function addItemServicoQuery (Doctrine_Query $q = null){

      if (is_null($q)) {
        $q = Doctrine_Query::create()
          ->from('Servico_item j');
      }

      $alias = $q->getRootAlias();

      return $q;
    }

}
