<?php

/**
 * servico_ufTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class servico_ufTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object servico_ufTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('servico_uf');
    }

     /*
    * Query predios com base nas siglas
    */
   public function addTipoPreventivaQuery(Doctrine_Query $q = null, $estado, $servico)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->select('j.preventiva_tipo_id AS preventiva_tipo_id')
         ->from('servico_uf j');
     }

     $alias = $q->getRootAlias();

     $q->leftJoin($alias.'.sfGuardUf a');
     $q->where('a.name = ?', $estado);
     $q->leftJoin($alias.'.Servico b');
     $q->andWhere('b.recurso_servico_requerido = ?', $servico);

     return $q;

   }

   /*
    * Retonar Tipo de preventiva
    */
   public function getTipoPreventiva(Doctrine_Query $q = null, $estado, $servico)
   {
       return $this->addTipoPreventivaQuery($q, $estado, $servico)->execute(array(), Doctrine::HYDRATE_SCALAR);
   }
 
}