<?php

/**
 * servico_grupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class servico_grupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object servico_grupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('servico_grupo');
    }
}