<?php

/**
 * sfGuardContractAfiliadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardContractAfiliadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardContractAfiliadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardContractAfiliado');
    }
}