<?php

/**
 * sfGuardUfAfiliadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUfAfiliadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUfAfiliadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUfAfiliado');
    }
}