<?php

/**
 * sfGuardContract_fiscalizacao_cabecalhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardContract_fiscalizacao_cabecalhoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardContract_fiscalizacao_cabecalhoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardContract_fiscalizacao_cabecalho');
    }
}