<?php

/**
 * sfGuardGramAfiliadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGramAfiliadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGramAfiliadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGramAfiliado');
    }
}