<?php

/**
 * sla_financeiro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sla_financeiro extends Basesla_financeiro
{
	/**
  * Deletar todos os itens do sla na tabela correspondente
  */
   public function deleteOldSLA($table){
	    $q = Doctrine_Query::create()
			->from($table.' p')
			->delete()
			->where('p.sla_id = ?', $this->getId());

		Doctrine_Core::getTable($table)->deleteItensSLA($q);
   }

}