<?php

/**
 * sla_evidenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sla_evidenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sla_evidenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sla_evidencia');
    }
}