<?php

/**
 * sla_cabecalhoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sla_cabecalhoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sla_cabecalhoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sla_cabecalho');
    }
	
	
	/*Busca somente os cabeçalhos correspondentes a um tipo de manutenção
	*/
	
	public function getCabecalhos($manutencao)
    {
      $q = $this->createQuery('j')
         ->where('j.tipo_manutencao_id = ?', $manutencao);  
		 
      return $q->execute();
    }
}