<?php

/**
 * sla_financeiroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sla_financeiroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sla_financeiroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sla_financeiro');
    }
	
	
	public function getPreco( $filial)
   {
        return $this->addPrecoQuery( $filial)->execute();
   }
	
	
	
	  public function addPrecoQuery( $filial)
   {
      $q = Doctrine_Query::create()
      ->select('j.id, a.nome, a.id')
      ->from('sla_financeiro j');
     
      $alias = $q->getRootAlias();
      $q->innerJoin($alias.'.fornecedor a');
      $q->andWhere('j.id = ?', $filial);

    
     return $q;
   }
	
	
	
	public function getDadosSla(){
        return $this->addSlaQuery()->execute();
	}
	
	public function addSlaQuery()
   {

     $q = Doctrine_Query::create()
     ->select('n.id, n.ano, a.nome')  
     ->from('sla_financeiro n');
    
	 $alias = $q->getRootAlias();
     $q->leftJoin($alias.'.fornecedor a');	

      return $q;

   }    
   
  
   public function getDadosSlaEspecifico($idSla){
        return $this->addDadosSlaEspecificoQuery($idSla)->execute();
	}
	
	public function addDadosSlaEspecificoQuery()
   {

     $q = Doctrine_Query::create()
     
     ->from('sla_financeiro n');
    
	 $alias = $q->getRootAlias();
     $q->innerJoin($alias.'.fornecedor a');	

      return $q;

   } 


   /*
   * Retonar itens de uma determinado apuracao de Manutencao
   */
   public function buscarSlaFinanceiro($ano, $filial)
   {
    return $this->addbuscarSlaFinanceiroQuery(null, $ano, $filial)->execute();
   }


   /*
    * Query para selecionar os itens de um determinado apuracao
    */
   public function addbuscarSlaFinanceiroQuery(Doctrine_Query $q = null, $ano, $filial)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sla_financeiro n');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.ano = ?', $ano);
     $q->andWhere($alias.'.filial_id = ?', $filial);

     return $q;
   }   
	
}