<?php

/**
 * sla_valores_totaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sla_valores_totaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sla_valores_totaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sla_valores_totais');
    }
	
	
	/*
	* Pega os valores que preenchem a tabela "amarela" ao final do SLA
	* Correspondente aos cálculos totais (por tipo de manutenção)
	*/

	public function getItensCalculoFinal($slaId)
   {
		 return $this->addItensQuery($slaId)->execute();
   }
	

	  public function addItensQuery($slaId)
   {
      $q = Doctrine_Query::create()
      ->from('sla_valores_totais');
     
      $q->where('sla_id = ?', $slaId);
      return $q;
   }


	public function getTotaisPorMes($slaId, $mes, $tipoManutencao)
   {
		return $this->addTotaisQuery($slaId, $mes, $tipoManutencao)->execute();
   }
	

	  public function addTotaisQuery($slaId, $mes, $tipoManutencao)
   {
      $q = Doctrine_Query::create()
      ->from('sla_valores_totais');
     
      $q->andWhere('sla_id = ?', $slaId);
      $q->andWhere('mes_id = ?', $mes);
      $q->andWhere('tipo_manutencao_id = ?', $tipoManutencao);
      return $q;
   }


    /*
    * Retonar preco do servico da PINI
    */
   public function getMesesSla(Doctrine_Query $q = null, $slaId, $tipoManutencao)
   {
        return $this->addMesesQuery($q, $slaId, $tipoManutencao)->execute(array(), Doctrine::HYDRATE_SCALAR);
   }
   
   
   public function addMesesQuery(Doctrine_Query $q = null, $slaId, $tipoManutencao)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sla_valores_totais j');
     }

     $alias = $q->getRootAlias();

     $q->innerJoin($alias.'.meses_ano a');
     $q->andWhere('j.sla_id = ?', $slaId);
     $q->andWhere('j.tipo_manutencao_id = ?', $tipoManutencao);
     
	 $q->orderBy('a.id ASC');

    
     return $q;
   }

   /*
    * Deletar todos os itens do sla na tabela correspondente
    */
    public function deleteItensSLA(Doctrine_Query $q = null) {
        $this->addItensTotaisQuery($q)->execute();
    }

   /*
    * Buscar sla totais limpeza
    */
    protected function addItensTotaisQuery(Doctrine_Query $q = null){

      if (is_null($q)) {
        $q = Doctrine_Query::create()
          ->from('sla_valores_totais s');
      }

      $alias = $q->getRootAlias();

      return $q;
    }

  

}