<?php

/**
 * sla_evidencia_manutencaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sla_evidencia_manutencaoTable extends sla_evidenciaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sla_evidencia_manutencaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sla_evidencia_manutencao');
    }
	
	
	/*
	*  EVIDENCIAS DE DETERMINADO MÊS
	*/
	public function getEvidencias($slaId, $mes){
		$q = $this->createQuery('j')
         ->where('j.sla_id= ?', $slaId)
		 ->andWhere('j.mes_referencia = ?', $mes);	
		 
      return $q->execute();
	}	
	
	
	/*
	*  TODAS AS EVIDENCIAS DE DETERMINADO SLA
	*/
	
	public function getTodasEvidencias($slaId){
		$q = $this->createQuery('j')
         ->where('j.sla_id= ?', $slaId)
		 ->orderby('id ASC');
      return $q->execute();
	}

	/*
    * Deletar todos os itens do sla na tabela correspondente
    */
    public function deleteItensSLA(Doctrine_Query $q = null) {
        $this->addItensSLAEvidenciaQuery($q)->execute();
    }

   /*
    * Buscar sla evidencia limpeza
    */
    protected function addItensSLAEvidenciaQuery(Doctrine_Query $q = null){

      if (is_null($q)) {
        $q = Doctrine_Query::create()
          ->from('sla_evidencia_manutencao s');
      }

      $alias = $q->getRootAlias();

      return $q;
    }
	

  /*
   * Retonar itens de uma determinado evidencia de Manutencao
   */
   public function getItensEvidencia($id)
   {
     return $this->addItensEvidenciaQuery(null, $id)->execute();
   }


   /*
    * Query para selecionar os itens de um determinado apuracao
    */
   public function addItensEvidenciaQuery(Doctrine_Query $q = null, $id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sla_evidencia_manutencao f');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.sla_id = ?', $id);

     return $q;
   }
	
	
}