<?php

/**
 * slaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class slaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object slaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sla');
    }

     /*
   * Retonar extintor de um determinado fiscalizacao
   */
   public function getSLAFiscalizacao($fiscalizacao_id)
   {
    return $this->addSLAFiscalizacaoQuery(null, $fiscalizacao_id)->execute();
   }


   /*
    * Query para selecionar os extintores de um determinado fiscalizacao
    */
   public function addSLAFiscalizacaoQuery(Doctrine_Query $q = null, $fiscalizacao_id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sla s');
     }

     $alias = $q->getRootAlias(); 
     $q->andWhere($alias.'.fiscalizacao_id = ?', $fiscalizacao_id);

     return $q;
   } 

   /**
     * Retorna os sla de um determinada fiscalizacao
     *
     * @return array sla
     */
    public function getSLA(Doctrine_Query $q = null)
    {
      if (is_null($q))
      {
        $q = Doctrine_Query::create()
          ->from('sla s');
      }
   
      return $q->execute();
    }
}