<?php

/**
 * tipo_avaliacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tipo_avaliacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tipo_avaliacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tipo_avaliacao');
    }
}

