<?php

/**
 * sfGuardUfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUfTable extends PluginsfGuardUfTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUf');
    }

 /*
    * Retonar chamados ativos
    */
   public function getUf(Doctrine_Query $q = null, $uf)
   {
    return $this->addUfQuery($q, $uf)->execute();
   }

   /*
    * Query chamados ativos
    */
   public function addUfQuery(Doctrine_Query $q = null, $uf)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sfGuardUf j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.name = ?', $uf);

     $q->orderBy($alias.'.created_at DESC');

      return $q;
   }
   
   	public function getEstados() {
		$q = $this->createQuery('c');
		return $q->execute();
	}

	
	
	
	public function getNomeUf($id)
   {
    return $this->addNomeUf($id)->execute();
   }
   
       public function addNomeUf($id)
   {
  		$q = Doctrine_Query::create()
		->select('n.name')	
  		->from('sfGuardUf n')
  		->where('id = ?', $id);
      
	  return $q;

   }  
	
	
	
}
