<?php

/**
 * sfGuardUserContractTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserContractTable extends PluginsfGuardUserContractTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserContractTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserContract');
    }
}