<?php

/**
 * sfGuardUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserPermissionTable extends PluginsfGuardUserPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserPermission');
    }
	
	public function temPermissao($user)
   {
     return $this->addTemPermissao($user)->execute();
   }
	
	
	public static function addTemPermissao($user){
    	$q = Doctrine_Query::create()
			->select('name')	
    		->from('sfGuardPermission u')
			->leftJoin('u.sfGuardUserPermission g')
    		->where('g.user_id = ?', $user);

    	return $q;	
	}
}












