<?php

/**
 * sfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroup');
    }

 /*
   * Retonar usuarios de acordo com o grupo que pertence e a regiao
   */
   public function getGroup(Doctrine_Query $q = null, $grupo)
   {
    return $this->addGroupQuery($q, $grupo)->execute();
   }


   /*
    * Query para recuperar usuarios especificos
    */
   public function addGroupQuery(Doctrine_Query $q = null, $grupo)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sfGuardGroup j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.name = ?', $grupo);

     $q->orderBy($alias.'.created_at DESC');

      return $q;
   }

}
