<?php

/**
 * sfGuardUserUfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserUfTable extends PluginsfGuardUserUfTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserUfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserUf');
    }
}