<?php

/**
 * sfGuardUfGramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUfGramTable extends PluginsfGuardUfGramTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUfGramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUfGram');
    }
	
	
	public function getGram(){
		return $this->addGram()->execute();
	}
	
	public function addGram(){
		$q = Doctrine_Query::create()
         ->from('SfGuardGram j')
		 ->orderBy('name asc');
      
      return $q;
	}

}