<?php

/**
 * sfGuardGramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGramTable extends PluginsfGuardGramTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGram');
    }

 /*
   * Retonar usuarios de acordo com o grupo que pertence e a regiao
   */
   public function getGram(Doctrine_Query $q = null, $gram)
   {
    return $this->addGramQuery($q, $gram)->execute();
   }


   /*
    * Query para recuperar usuarios especificos
    */
   public function addGramQuery(Doctrine_Query $q = null, $gram)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sfGuardGram j');
     }

     $alias = $q->getRootAlias();
     $q->andWhere($alias.'.name = ?', $gram);
     $q->limit(1);

      return $q;
   }



 /**
  *Retorna o id do gram baseado no nome dele
  */
  public function getIdGram($nomeGram) 
  {
    $q = Doctrine_Query::create()
      ->select('id')
      ->from('sfGuardGram')
      ->where('name = ?', $nomeGram);
     
    return $q->execute();     
    
  }

  
  public function getTelegramId($gram) 
  {
    $q = Doctrine_Query::create()
      ->select('telegram_id')
      ->from('sfGuardGram')
      ->where('name = ?', $gram);
     
    return $q->execute();     
    
  }
  
}
