<?php

/**
 * sfGuardLastPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardLastPasswordTable extends PluginsfGuardLastPasswordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardLastPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardLastPassword');
    }
}