<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{

    static protected $usuarios = array();

    /*
     * Retonar opcoes para o campo usuario
     */
    public function getTypes()
    {
      return self::$usuarios;
    }

    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    /**
    * Retorna objeto do tipo Usuario
    */ 
    public function getUsuariosSimplificado (Doctrine_Query $q = null) {
        return $this->addUsuariosQuerySimplificado($q)->execute();
    }

    /**
    * Query padrao
    */
    public function addUsuariosQuerySimplificado (Doctrine_Query $q = null) {

      if (is_null($q)) {
        $q = Doctrine_Query::create()
           ->from('sfGuardUser u');
      }

      $alias = $q->getRootAlias();

      $q->andWhere('u.is_active = ?', true);

      return $q;
    }


 /*
   * Retonar usuarios de acordo com o grupo que pertence e a regiao
   */
   public function getUsuarios(Doctrine_Query $q = null, $grupo, $uf, $gram, $contrato)
   {
    return $this->addUsuariosQuery($q, $grupo, $uf, $gram, $contrato)->execute();
   }


   /*
    * Query para recuperar usuarios especificos
    */
   public function addUsuariosQuery(Doctrine_Query $q = null, $grupo, $uf, $gram, $contrato)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sfGuardUser j');
     }

     $alias = $q->getRootAlias();

     $q->innerJoin($alias.'.sfGuardUserUf a');
     $q->andWhere('a.uf_id = "'.$uf.'"');

     $q->innerJoin($alias.'.sfGuardUserGram b');
     $q->andWhere('b.gram_id = "'.$gram.'"');

     $q->innerJoin($alias.'.sfGuardUserContract c');
     $q->andWhere('c.contract_id = "'.$contrato.'"');

     $q->innerJoin($alias.'.sfGuardUserGroup d');
     $q->andWhere('d.group_id = "'.$grupo.'"');

     $q->orderBy($alias.'.created_at DESC');

      return $q;
   }

  /*
   * Retonar oficiais de acordo com o estado, gram e contrato que pertecem
   */
   public function getOficiais(Doctrine_Query $q = null, $gram, $permissao)
   {
    return $this->addOficiaisQuery($q, $gram[0]->getId(), $permissao[0]->getId())->execute();
   }


   /*
    * Query para recuperar usuarios especificos
    */
   public function addOficiaisQuery(Doctrine_Query $q = null, $gram_id, $permissao_id)
   {
     if (is_null($q))
     {
      $q = Doctrine_Query::create()
         ->from('sfGuardUser j');
     }

     $alias = $q->getRootAlias();

     $q->leftJoin($alias.'.sfGuardUserGram b');
     $q->andWhere('b.gram_id = "'.$gram_id.'"');

     $q->leftJoin($alias.'.sfGuardUserPermission d');
     $q->andWhere('d.permission_id = "'.$permissao_id.'"');

     $q->orderBy($alias.'.created_at DESC');

      return $q;
   }

  
   
    public function getNomeUser($id){
       return $this->hasNome($id)->execute();
    }
   
	public function hasNome($id){
	   $q = Doctrine_Query::create()
	    ->select('p.first_name, p.last_name')
        ->from('sfGuardUser p')
        ->where('p.id = ?', $id);
       
      return $q; 
	} 
}
