<?php

/**
 * sfGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardPermission');
    }

    /**
    * Retorna um objeto do tipo Permission a partir do nome da permissao
    */
    public function getPermission (Doctrine_Query $q = null, $permission) {
      	return $this->addPermissionQuery($q, $permission)->execute();
    }

    /**
    * Retorna um objeto do tipo Query
    */
    public function addPermissionQuery (Doctrine_Query $q = null, $permission) {
    	
    	if (is_null($q)) {
    		$q = Doctrine_Query::create()
    			->from('sfGuardPermission p');
    	}

    	$alias = $q->getRootAlias();
        $q->where('p.name = ?', $permission);

    	return $q;
    }



}