<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{

	/**
	* Retorna uma String da concatenacao do Primeiro com o Ultimo nome do Usuario
	*/
	public function getNomeConcatenado () {
		return $this->getFirstName() . " " . $this->getLastName();
	}

}
