<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property timestamp $expires_at
 * @property varchar $phone
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Uf
 * @property Doctrine_Collection $Contract
 * @property Doctrine_Collection $Gram
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property sfGuardLastPassword $sfGuardLastPassword
 * @property Doctrine_Collection $sfGuardUserUf
 * @property Doctrine_Collection $sfGuardUserContract
 * @property Doctrine_Collection $sfGuardUserGram
 * @property Doctrine_Collection $Oficial
 * @property Doctrine_Collection $Usuarios
 * @property Doctrine_Collection $FopAplicouSla
 * 
 * @method string                getFirstName()             Returns the current record's "first_name" value
 * @method string                getLastName()              Returns the current record's "last_name" value
 * @method string                getEmailAddress()          Returns the current record's "email_address" value
 * @method string                getUsername()              Returns the current record's "username" value
 * @method string                getAlgorithm()             Returns the current record's "algorithm" value
 * @method string                getSalt()                  Returns the current record's "salt" value
 * @method string                getPassword()              Returns the current record's "password" value
 * @method boolean               getIsActive()              Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()             Returns the current record's "last_login" value
 * @method timestamp             getExpiresAt()             Returns the current record's "expires_at" value
 * @method varchar               getPhone()                 Returns the current record's "phone" value
 * @method Doctrine_Collection   getGroups()                Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()           Returns the current record's "Permissions" collection
 * @method Doctrine_Collection   getUf()                    Returns the current record's "Uf" collection
 * @method Doctrine_Collection   getContract()              Returns the current record's "Contract" collection
 * @method Doctrine_Collection   getGram()                  Returns the current record's "Gram" collection
 * @method Doctrine_Collection   getSfGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()      Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()          Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()        Returns the current record's "ForgotPassword" value
 * @method sfGuardLastPassword   getSfGuardLastPassword()   Returns the current record's "sfGuardLastPassword" value
 * @method Doctrine_Collection   getSfGuardUserUf()         Returns the current record's "sfGuardUserUf" collection
 * @method Doctrine_Collection   getSfGuardUserContract()   Returns the current record's "sfGuardUserContract" collection
 * @method Doctrine_Collection   getSfGuardUserGram()       Returns the current record's "sfGuardUserGram" collection
 * @method Doctrine_Collection   getOficial()               Returns the current record's "Oficial" collection
 * @method Doctrine_Collection   getUsuarios()              Returns the current record's "Usuarios" collection
 * @method Doctrine_Collection   getFopAplicouSla()         Returns the current record's "FopAplicouSla" collection
 * @method sfGuardUser           setFirstName()             Sets the current record's "first_name" value
 * @method sfGuardUser           setLastName()              Sets the current record's "last_name" value
 * @method sfGuardUser           setEmailAddress()          Sets the current record's "email_address" value
 * @method sfGuardUser           setUsername()              Sets the current record's "username" value
 * @method sfGuardUser           setAlgorithm()             Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                  Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()              Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()              Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()             Sets the current record's "last_login" value
 * @method sfGuardUser           setExpiresAt()             Sets the current record's "expires_at" value
 * @method sfGuardUser           setPhone()                 Sets the current record's "phone" value
 * @method sfGuardUser           setGroups()                Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()           Sets the current record's "Permissions" collection
 * @method sfGuardUser           setUf()                    Sets the current record's "Uf" collection
 * @method sfGuardUser           setContract()              Sets the current record's "Contract" collection
 * @method sfGuardUser           setGram()                  Sets the current record's "Gram" collection
 * @method sfGuardUser           setSfGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()      Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()          Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()        Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setSfGuardLastPassword()   Sets the current record's "sfGuardLastPassword" value
 * @method sfGuardUser           setSfGuardUserUf()         Sets the current record's "sfGuardUserUf" collection
 * @method sfGuardUser           setSfGuardUserContract()   Sets the current record's "sfGuardUserContract" collection
 * @method sfGuardUser           setSfGuardUserGram()       Sets the current record's "sfGuardUserGram" collection
 * @method sfGuardUser           setOficial()               Sets the current record's "Oficial" collection
 * @method sfGuardUser           setUsuarios()              Sets the current record's "Usuarios" collection
 * @method sfGuardUser           setFopAplicouSla()         Sets the current record's "FopAplicouSla" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('phone', 'varchar', 20, array(
             'type' => 'varchar',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUf as Uf', array(
             'refClass' => 'sfGuardUserUf',
             'local' => 'user_id',
             'foreign' => 'uf_id'));

        $this->hasMany('sfGuardContract as Contract', array(
             'refClass' => 'sfGuardUserContract',
             'local' => 'user_id',
             'foreign' => 'contract_id'));

        $this->hasMany('sfGuardGram as Gram', array(
             'refClass' => 'sfGuardUserGram',
             'local' => 'user_id',
             'foreign' => 'gram_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardLastPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserUf', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserContract', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGram', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Checklist as Oficial', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('fiscalizacao as Usuarios', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sla_financeiro as FopAplicouSla', array(
             'local' => 'id',
             'foreign' => 'fop_responsavel_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}