<?php

/**
 * BasesfGuardUserUf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $uf_id
 * @property sfGuardUser $User
 * @property sfGuardUf $Uf
 * 
 * @method integer       getUserId()  Returns the current record's "user_id" value
 * @method integer       getUfId()    Returns the current record's "uf_id" value
 * @method sfGuardUser   getUser()    Returns the current record's "User" value
 * @method sfGuardUf     getUf()      Returns the current record's "Uf" value
 * @method sfGuardUserUf setUserId()  Sets the current record's "user_id" value
 * @method sfGuardUserUf setUfId()    Sets the current record's "uf_id" value
 * @method sfGuardUserUf setUser()    Sets the current record's "User" value
 * @method sfGuardUserUf setUf()      Sets the current record's "Uf" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserUf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_uf');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('uf_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUf as Uf', array(
             'local' => 'uf_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}