<?php

/**
 * BasesfGuardUf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $state
 * @property Doctrine_Collection $Cabecalho
 * @property Doctrine_Collection $preventiva_tipo
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Grams
 * @property Doctrine_Collection $sfGuardUserUf
 * @property Doctrine_Collection $sfGuardUfGram
 * @property Doctrine_Collection $sfGuardBdi
 * @property Doctrine_Collection $Tipo_Ufs
 * @property Doctrine_Collection $PiniUf
 * @property Doctrine_Collection $preventiva_tipo_uf
 * @property Doctrine_Collection $cabecalho_uf
 * @property Doctrine_Collection $Afiliados
 * @property Doctrine_Collection $sfGuardUfAfiliado
 * @property Doctrine_Collection $Ufs
 * @property Doctrine_Collection $contratoUf
 * @property Doctrine_Collection $SlaUf
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getState()              Returns the current record's "state" value
 * @method Doctrine_Collection getCabecalho()          Returns the current record's "Cabecalho" collection
 * @method Doctrine_Collection getPreventivaTipo()     Returns the current record's "preventiva_tipo" collection
 * @method Doctrine_Collection getUsers()              Returns the current record's "Users" collection
 * @method Doctrine_Collection getGrams()              Returns the current record's "Grams" collection
 * @method Doctrine_Collection getSfGuardUserUf()      Returns the current record's "sfGuardUserUf" collection
 * @method Doctrine_Collection getSfGuardUfGram()      Returns the current record's "sfGuardUfGram" collection
 * @method Doctrine_Collection getSfGuardBdi()         Returns the current record's "sfGuardBdi" collection
 * @method Doctrine_Collection getTipoUfs()            Returns the current record's "Tipo_Ufs" collection
 * @method Doctrine_Collection getPiniUf()             Returns the current record's "PiniUf" collection
 * @method Doctrine_Collection getPreventivaTipoUf()   Returns the current record's "preventiva_tipo_uf" collection
 * @method Doctrine_Collection getCabecalhoUf()        Returns the current record's "cabecalho_uf" collection
 * @method Doctrine_Collection getAfiliados()          Returns the current record's "Afiliados" collection
 * @method Doctrine_Collection getSfGuardUfAfiliado()  Returns the current record's "sfGuardUfAfiliado" collection
 * @method Doctrine_Collection getUfs()                Returns the current record's "Ufs" collection
 * @method Doctrine_Collection getContratoUf()         Returns the current record's "contratoUf" collection
 * @method Doctrine_Collection getSlaUf()              Returns the current record's "SlaUf" collection
 * @method sfGuardUf           setName()               Sets the current record's "name" value
 * @method sfGuardUf           setState()              Sets the current record's "state" value
 * @method sfGuardUf           setCabecalho()          Sets the current record's "Cabecalho" collection
 * @method sfGuardUf           setPreventivaTipo()     Sets the current record's "preventiva_tipo" collection
 * @method sfGuardUf           setUsers()              Sets the current record's "Users" collection
 * @method sfGuardUf           setGrams()              Sets the current record's "Grams" collection
 * @method sfGuardUf           setSfGuardUserUf()      Sets the current record's "sfGuardUserUf" collection
 * @method sfGuardUf           setSfGuardUfGram()      Sets the current record's "sfGuardUfGram" collection
 * @method sfGuardUf           setSfGuardBdi()         Sets the current record's "sfGuardBdi" collection
 * @method sfGuardUf           setTipoUfs()            Sets the current record's "Tipo_Ufs" collection
 * @method sfGuardUf           setPiniUf()             Sets the current record's "PiniUf" collection
 * @method sfGuardUf           setPreventivaTipoUf()   Sets the current record's "preventiva_tipo_uf" collection
 * @method sfGuardUf           setCabecalhoUf()        Sets the current record's "cabecalho_uf" collection
 * @method sfGuardUf           setAfiliados()          Sets the current record's "Afiliados" collection
 * @method sfGuardUf           setSfGuardUfAfiliado()  Sets the current record's "sfGuardUfAfiliado" collection
 * @method sfGuardUf           setUfs()                Sets the current record's "Ufs" collection
 * @method sfGuardUf           setContratoUf()         Sets the current record's "contratoUf" collection
 * @method sfGuardUf           setSlaUf()              Sets the current record's "SlaUf" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_uf');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('state', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cabecalho', array(
             'refClass' => 'cabecalho_uf',
             'local' => 'uf_id',
             'foreign' => 'cabecalho_id'));

        $this->hasMany('preventiva_tipo', array(
             'refClass' => 'preventiva_tipo_uf',
             'local' => 'uf_id',
             'foreign' => 'preventiva_tipo_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserUf',
             'local' => 'uf_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardGram as Grams', array(
             'refClass' => 'sfGuardUfGram',
             'local' => 'uf_id',
             'foreign' => 'gram_id'));

        $this->hasMany('sfGuardUserUf', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('sfGuardUfGram', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('sfGuardBdi', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('servico_uf as Tipo_Ufs', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('preco as PiniUf', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('preventiva_tipo_uf', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('cabecalho_uf', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('Afiliado as Afiliados', array(
             'refClass' => 'sfGuardUfAfiliado',
             'local' => 'uf_id',
             'foreign' => 'afiliado_id'));

        $this->hasMany('sfGuardUfAfiliado', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('notificacao as Ufs', array(
             'local' => 'id',
             'foreign' => 'uf_id'));

        $this->hasMany('contrato_fornecedor as contratoUf', array(
             'local' => 'id',
             'foreign' => 'filial_id'));

        $this->hasMany('sla_financeiro as SlaUf', array(
             'local' => 'id',
             'foreign' => 'filial_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}