<?php

/**
 * BasesfGuardUserContract
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $contract_id
 * @property sfGuardUser $User
 * @property sfGuardContract $Contract
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getContractId()  Returns the current record's "contract_id" value
 * @method sfGuardUser         getUser()        Returns the current record's "User" value
 * @method sfGuardContract     getContract()    Returns the current record's "Contract" value
 * @method sfGuardUserContract setUserId()      Sets the current record's "user_id" value
 * @method sfGuardUserContract setContractId()  Sets the current record's "contract_id" value
 * @method sfGuardUserContract setUser()        Sets the current record's "User" value
 * @method sfGuardUserContract setContract()    Sets the current record's "Contract" value
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserContract extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_contract');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('contract_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardContract as Contract', array(
             'local' => 'contract_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}