<?php

/**
 * BasesfGuardGram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $region
 * @property integer $telegram_id
 * @property Doctrine_Collection $Uf
 * @property Telegram $Telegram
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $sfGuardUserGram
 * @property Doctrine_Collection $sfGuardUfGram
 * @property Doctrine_Collection $Afiliados
 * @property Doctrine_Collection $sfGuardGramAfiliado
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getRegion()              Returns the current record's "region" value
 * @method integer             getTelegramId()          Returns the current record's "telegram_id" value
 * @method Doctrine_Collection getUf()                  Returns the current record's "Uf" collection
 * @method Telegram            getTelegram()            Returns the current record's "Telegram" value
 * @method Doctrine_Collection getUsers()               Returns the current record's "Users" collection
 * @method Doctrine_Collection getSfGuardUserGram()     Returns the current record's "sfGuardUserGram" collection
 * @method Doctrine_Collection getSfGuardUfGram()       Returns the current record's "sfGuardUfGram" collection
 * @method Doctrine_Collection getAfiliados()           Returns the current record's "Afiliados" collection
 * @method Doctrine_Collection getSfGuardGramAfiliado() Returns the current record's "sfGuardGramAfiliado" collection
 * @method sfGuardGram         setName()                Sets the current record's "name" value
 * @method sfGuardGram         setRegion()              Sets the current record's "region" value
 * @method sfGuardGram         setTelegramId()          Sets the current record's "telegram_id" value
 * @method sfGuardGram         setUf()                  Sets the current record's "Uf" collection
 * @method sfGuardGram         setTelegram()            Sets the current record's "Telegram" value
 * @method sfGuardGram         setUsers()               Sets the current record's "Users" collection
 * @method sfGuardGram         setSfGuardUserGram()     Sets the current record's "sfGuardUserGram" collection
 * @method sfGuardGram         setSfGuardUfGram()       Sets the current record's "sfGuardUfGram" collection
 * @method sfGuardGram         setAfiliados()           Sets the current record's "Afiliados" collection
 * @method sfGuardGram         setSfGuardGramAfiliado() Sets the current record's "sfGuardGramAfiliado" collection
 * 
 * @package    usuario
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardGram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_gram');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('region', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('telegram_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUf as Uf', array(
             'refClass' => 'sfGuardUfGram',
             'local' => 'gram_id',
             'foreign' => 'uf_id'));

        $this->hasOne('Telegram', array(
             'local' => 'telegram_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserGram',
             'local' => 'gram_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGram', array(
             'local' => 'id',
             'foreign' => 'gram_id'));

        $this->hasMany('sfGuardUfGram', array(
             'local' => 'id',
             'foreign' => 'gram_id'));

        $this->hasMany('Afiliado as Afiliados', array(
             'refClass' => 'sfGuardGramAfiliado',
             'local' => 'gram_id',
             'foreign' => 'afiliado_id'));

        $this->hasMany('sfGuardGramAfiliado', array(
             'local' => 'id',
             'foreign' => 'gram_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}